### ISSUE TITLE
Parallelize computeThetas to reduce training time

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#10]
**Is your feature request related to a problem? Please describe.**
Training time can be reduced by using worker_threads (when available based on the node version).

**Describe the solution you'd like**
Computing Thetas does a descend of gradient that is unique for each classification label, so the calculation of the theta can be theorically executed threaded:

https://github.com/axa-group/nlp.js/blob/master/lib/math/mathops.js#L165

**Comment by vvscode** [comment]
@jesus-seijas-sp sorry, I'm novice in projce

about calculation theta: https://github.com/axa-group/nlp.js/blob/master/lib/math/mathops.js#L164 - there is no calculations in fact. Just new array creation.

So I you're talking about `descendGradient` (L165)

Is there a dataset to get valuable time changes?

**Comment by jesus-seijas-sp** [comment]
Hello! Sorry, my fault, the code changed since the issue was opened. 
In fact yes, is descendGradient the calculation that can be parallelized.
To understand how to test and how to benchmark:
The computeThetas executes a loop for iteraint each different classification (intent). So if you have an example classificating several phrases into 2 different intents, the compute thetas will call descendGradient twice. In the /example/console-bot there is a training with lots of intents, in my laptop the training takes 12 seconds. As my laptop have 4 cores, it can theorically be reduced to 3 seconds by parallelizing descendGradient as the gradient descend is unique for each intent.

As worker_threads is still an experimental feature, this task is also an experiment, and is not critical. 
There are other ways to parallelize it, but means using C++ and the N-API.

If you need more information don't hesitate on ask. And thank you!

**Comment by vvscode** [comment]
https://nodejs.org/api/worker_threads.html is part of Node (at least 10)

**Comment by vvscode** [comment]
`Mathops.computeThetas` /  `Classifier.prototype.train` should become async (possibly other methods too )

do you agree?

**Comment by jesus-seijas-sp** [comment]
Yes, I agree!

**Comment by vvscode** [comment]
@jesus-seijas-sp  what about the way, how to switch logic for parallel computing?

For me there two major ways:
1. Param for `NlpClassifier` instance
1. Global env-variable

- `.computeThetas` never calls directly, and passing params might be non-obvious and tricky
- using global flags even less obvious, and not good design pattern in general

What are your thoughts?

**Comment by jesus-seijas-sp** [comment]
@vvscode Usually in libraries I recommend settings param and not environment, to not affect the platform behaviour, but with exceptions:
- NODE_ENV can be always taked into account
- Environment variables related to the relationship between the library and the SO, like number of threads for a pool.
In this case I think that fits the second option, but given the fact that is a library, a fallback chain can be used, like:
```javascript
this.parallelComputing = settings.parallelComputing || process.env.NLPJS_PARALLEL_COMPUTING || false;
```

Also, as information, there is a trending library for abstract the use of worker_threads: https://www.npmjs.com/package/microjob

**Comment by jesus-seijas-sp** [comment]
@vvscode Sorry for being late! I see in travis that you got it working. Still need help?

**Comment by vvscode** [comment]
Nope. Currently in tranvis it uses only `single thread` version. The diff - to use `workers` you have to call node with param `--experimental-worker` otherwise even `microjob` won't work.

So just for node-10 there should be an extra case when it runs with `node --experimental-worker node_modules/.bin/jest`

Not sure if we really need this case. It's better to read comments and check version from https://github.com/axa-group/nlp.js/pull/72

If there is no need to test case for multithread - just try run console-bot and compare speed /  results

**Comment by jesus-seijas-sp** [comment]
If having the tests passing in travis with experimental features will be a headache, I agree that CI tests can be done without working_threads, and to do the check locally. Also, node 11 will arrive in 20 days, I expect it to bring working_threads without experimental. If not... well, we can wait.

**Comment by jesus-seijas-sp** [comment]
Solved with https://github.com/axa-group/nlp.js/pull/72
