### ISSUE TITLE
can not get values from context

### ISSUE THREAD

**Issue by TobiasNickel** [axa-group/nlp.js#1001]
**Describe the bug**
The context does not work as described here: https://github.com/axa-group/nlp.js/blob/master/docs/v3/nlp-manager.md#context

**To Reproduce**

1. create a directory and go into it
2. run # echo {} > package.json
3. run # cat node_modules/node-nlp/package.json 
4. see that there is version 4.22.1
5. run # npm install --save node-nlp
6. run # vim test1.js
7. past the context example from the following link into the file: https://github.com/axa-group/nlp.js/blob/master/docs/v3/nlp-manager.md#context
8. save and exit vim with ":wq"
9. run # node test1.js
10. the console print training epochs and `Till next time, {{name}}`.

This was tested on a intel/MAC and in a Linux online VM (1&1).

**Expected behavior**
I expected to see in the end that it prints: `Till next time, John`.

**Screenshots**
![1463988335](https://user-images.githubusercontent.com/4189801/142957629-77c69fd4-975c-45f1-9a17-17f0fdcf2fa8.jpg)

**Desktop:**
 - OS: macOS and Linux
 - Browser: Node.js
 - Package version: 4.22.1
 - Node version 12 in mac, 15.6.0 in linux

**Additional context**
I also cloned this repo, run the post install script, it failed in private Windows10 machine: it could not compile tensor flow.

I cloned this repo on the linux VM, I was able to complete the postinstall script (lerna bootstrap) and run the tests(npm run test).
Then I added a new case to `packages/nlp/test/nlp.test.js` that contains the code from the context example (url above), expect the result.answer to equal `Till next time, John` and the test passed.

**Comment by eswarsaladi** [comment]
Same issue with me

**Comment by Apollon77** [comment]
Yes I also noticed this. The example is not wotking that way because there is no deifinition on how to exotract the entity from the text. Iin fact you need to add a "AfterLast" rule to tell NER how to "cut out" the word "John" from the text.
