### ISSUE TITLE
Customize Port with process.env.PORT for Heroku deployment

### ISSUE THREAD

**Issue by obiofiong** [axa-group/nlp.js#1003]
I want to deploy the chatbot to heroku but it keeps breaking upon deployment. 
I suspect that this is because the PORT is statically set to 3000 in the json config file..

How can I make it a variable such as process.env.PORT so that Heroku can automatically deploy it on their Port

**Comment by TobiasNickel** [comment]
This is a library, it does not care about a server and exposed ports. I think in Heroku, you need to use `process.env.PORT`.
But I think you would know this thing. Can you give us more details how you want to deploy your chatbot?

**Comment by ericzon** [comment]
As this question is already answered I close this topic.
