### ISSUE TITLE
Can't install with NPM (No matching version found for @nlpjs/evaluator@^4.22.2.)

### ISSUE THREAD

**Issue by fred2458** [axa-group/nlp.js#1031]
Hi, first of all, thanks fo all the work you do here. 
Today my jenkins process didn't compile, with the next error. To verify that it was a global problem I tryed to install in empty folder and I get the same result. So I guess that is a new bug.

**Describe the bug**
When I try to install library takes this error:

$ npm i @nlpjs/basic

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nlpjs/evaluator@^4.22.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@nlpjs/basic'
npm ERR! notarget 

**To Reproduce**
npm i @nlpjs/basic 
in a fresh folder
NPM Version: 6.14.4

**Comment by bkimminich** [comment]
Yep, same here ...

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nlpjs/language@^4.22.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@nlpjs/lang-all'
npm ERR! notarget
```

**Comment by bkimminich** [comment]
Seems a very thorough mess-up, because even pinning to a previous version stills runs into this issue...

```
 "dependencies": {
    "@nlpjs/core-loader": "4.4.0",
    "@nlpjs/evaluator": "4.4.0",
    "@nlpjs/lang-all": "4.4.0",
    "@nlpjs/language": "4.3.0",
    "@nlpjs/nlp": "4.4.0",
    "@nlpjs/nlu": "4.4.0",
    "@nlpjs/request": "4.4.0",
    "@nlpjs/sentiment": "4.4.0",
    "vm2": "3.9.3"
  },
```

still gives me

```
npm ERR! code ETARGET                                                         
npm ERR! notarget No matching version found for @nlpjs/language-min@^4.22.2.  
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@nlpjs/ner'
npm ERR! notarget 
```

**Comment by fred2458** [comment]
yep i tried to downgrade, and exactly the same

**Comment by bkimminich** [comment]
I supposed it'd work if we declared all the sub-deps directly to avoid them pulling any `^4.x.x` internally, but maybe they'll fix quickly enough to skip this pointless effort on our end... 😁

**Comment by fred2458** [comment]
could work, I'm near to do that xD

I read the code and currently evaluator package.json have his version in 4.22.2, but in npm last version published is 4.21.1.

https://github.com/axa-group/nlp.js/blob/master/packages/evaluator/package.json
https://www.npmjs.com/package/@nlpjs/evaluator

Something happened with npm, but it's out of my knowlage

**Comment by ericzon** [comment]
Sorry guys, we're investigating on it. Some hidden problem appeared during lerna publish magic... We'll try to have something working asap

**Comment by edwin-hendriks** [comment]
Great that you are working on it. I have the same issue and it would be nice not to have to spent time to get a workaround up and running.

**Comment by shawnho1018** [comment]
My error occurs at @nlpjs/language... I suspect it is the same issue. It broke 24 hours ago (It was working earlier). My error message is the same 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nlpjs/language@^4.22.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Also, npm only has the latest version up to 4.21.1: https://www.npmjs.com/package/@nlpjs/language

**Comment by obladio28** [comment]
I have the same problem (node-red)  node-red-contrib-chatbot@0.19.11

`-----------------------------------------------------------
2022-01-04T14:24:02.976Z Install : node-red-contrib-chatbot 0.19.11

2022-01-04T14:24:02.943Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-chatbot@0.19.11
2022-01-04T14:24:47.009Z [err] npm 
2022-01-04T14:24:47.009Z [err] WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
2022-01-04T14:25:14.000Z [err] npm ERR! code ETARGET
2022-01-04T14:25:14.007Z [err] npm ERR! notarget No matching version found for @nlpjs/language@^4.22.2.
2022-01-04T14:25:14.007Z [err] npm 
2022-01-04T14:25:14.007Z [err] ERR! notarget In most cases you or one of your dependencies are requesting
2022-01-04T14:25:14.007Z [err] npm ERR! notarget a package version that doesn't exist.
2022-01-04T14:25:14.007Z [err] npm ERR! notarget 
2022-01-04T14:25:14.007Z [err] npm ERR! notarget
2022-01-04T14:25:14.007Z [err]  It was specified as a dependency of '@nlpjs/lang-all'
2022-01-04T14:25:14.007Z [err] npm ERR! notarget 
2022-01-04T14:25:14.043Z [err] 
2022-01-04T14:25:14.043Z [err] npm ERR! A complete log of this run can be found in:
2022-01-04T14:25:14.043Z [err] npm ERR!     /data/.npm/_logs/2022-01-04T14_25_14_013Z-debug.log
2022-01-04T14:25:14.051Z rc=1`

**Comment by ericzon** [comment]
Guys, please, take a look. Now all these problems should be fixed.

**Comment by fred2458** [comment]
Works. Thanks a lot guys!!
