### ISSUE TITLE
nlp tf idf for recommend

### ISSUE THREAD

**Issue by huy1999dnbk** [axa-group/nlp.js#1040]
I am making recommend product based on lastest product in their lastest order. I am using tfidf to find common ground between products based on description using tf idf
i don't know if nlp.js supports tfidf, thanks a lot

**Comment by ericzon** [comment]
hello @huy1999dnbk in utils package a tf-idf implementation is included. Here I link you the tests to show how it works: https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/packages/utils/test/tfidf.test.js

**Comment by ericzon** [comment]
I close this as it's already answered
