### ISSUE TITLE
Some words such as "hey" doesn't get trained

### ISSUE THREAD

**Issue by saeho** [axa-group/nlp.js#116]
I noticed that some utterances such as "hey" never gets properly trained into the model. Therefore, I can never correctly get the intent for these utterances.

So far I discovered "hey" is one such word.

Are there other utterances that never gets trained into the model? If so, what are they? What are the rules in determining such utterances getting ignored?

**Comment by jesus-seijas-sp** [comment]
Hello @saeho,

I did a try, you can find the code and execute it here: https://runkit.com/jesus-seijas-sp/5be568932daea000117ca3ec

![image](https://user-images.githubusercontent.com/15154218/48264115-b584bc80-e428-11e8-9366-c724a66113a9.png)

As you can see "hey" is giving me a 0.9813.
Perhaps you can clone/edit my example in runkit to reproduce the issue so I can investigate.

**Comment by jesus-seijas-sp** [comment]
Close as it is answered
