### ISSUE TITLE
Sentiment analyzer with AFINN dictionary does not work on Linux

### ISSUE THREAD

**Issue by jnv** [axa-group/nlp.js#117]
I have bumped into an interesting behavior of sentiment analyzer. I have the following code with AFINN sentiment analyzer in Spanish:

```js
const nodeNlp = require('node-nlp')

const sentimentDetectorES = new nodeNlp.SentimentAnalyzer({
	language: 'es',
	type: 'AFINN',
})
const text = 'Te quiero mucho, eres lo mejor, amor.'
console.log(sentimentDetectorES.getSentiment(text))
```

Running this on macOS, this gets correctly identified with positive score:

```js
{ score: 6,
  numWords: 7,
  numHits: 2,
  comparative: 0.8571428571428571,
  type: 'AFINN',
  language: 'es' }
```

Running the same code on Linux (i.e. most servers) gives me zero score:

```js
{ score: 0,
  numWords: 7,
  numHits: 0,
  comparative: 0,
  type: 'AFINN',
  language: 'es' }
```

You can run this on RunKit to reproduce the behavior: https://runkit.com/embed/tgxf9t9yh5wj

This seems to affect also English AFFIN analyzer, but the default senticon analyzer works correctly on both platforms.

----

- Tested OSs: macOS 10.14.1, Debian Jessie x64
- Affected Node versions: v8.12.0, v10.13.0, v9.11.2

**Comment by jesus-seijas-sp** [comment]
Hello, 
it seems to be the case sensitiveness of the SO. The files for afinn have the format "afinn_es".

Here you have a RunKit fixed: https://runkit.com/jesus-seijas-sp/5be560f0df1fed0012810a7b

**Comment by jnv** [comment]
Excellent, that makes perfect sense. Thank you Jesús!
