### ISSUE TITLE
Slot filling

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#12]
**Is your feature request related to a problem? Please describe.**
Currently we can know the entities related to a given intent by the text in the intent, and the intent structure will have the names of the entities so can be extracted.
The idea is to have slot filling, that is: for each entity we should know if is mandatory or optional, and in case of mandatory for each language we should have the question that the chatbot should ask to the user when the slot is not filled.

Example: Whe have the intent **travel** and 2 entities: **location** and **date**. There are four types of conversation:
1. The user fills all the slots 
user> I want to travel *tomorrow* to *London*
bot> Ok, preparing your travel to London for 27/08/2028

2. The user fills date slot:
user> I want to travel *tomorrow*
bot> What is your destination?
user> London
bot> Ok, preparing your travel to London for 27/08/2028

3. The user fills location slot:
user> I want to travel to London
bot> When do you want to travel to London? 
user> I want to travel tomorrow
bot> Ok, preparing your travel to London for 27/08/2028

4. The user does not fill any slot
user> I want to travel to London
bot> What is your destination?
user> I want to go to London
bot> When do you want to travel to London? 
user> I want to travel tomorrow
bot> Ok, preparing your travel to London for 27/08/2028

**Describe the solution you'd like**
I think that can be implemented as a slot manager, so a new hard entity slot should be defined, and inside the NLP manager an implementation of the slot manager is given. Questions in the slots should be templated so they can use things from the context (as in the example when it say *When do you want to travel to London* ).
Also, the Microsoft Bot Framework Recognizer will need a hard work so when an answer is received with slots to fill, it should be able to take control of the dialog inserting a new artificial prompt or a new dialog state. About where the logic should be implemented, I think that should be send to the NLP manager as contextualized information. The reason is: imagine the previous example the user does not fill any slot so 2 slot questions are received, if the logic for both questions is at the recognizer and in the first question the user answer the 2 slots, the recognizer will not know and will answer the date even if the user already provided it.

**Comment by lolo8304** [comment]
Question: had this issue. When do you consider to clear the slots? Sometimes it makes sense to keep and still fillings slots. Sometimes not. 
The dialog - context - Szenario should control the slots, store them in stacks, free them if needed, until fulfilled. 

There should be dialogs with ‘no slot usage or slot filling’. Should be co figured by dialog

**Comment by jesus-seijas-sp** [comment]
@lolo8304 My idea was to take consideration of the architecture of Microsoft Bot Framework with the dialogStack. That way, you can trigger an intent that perhaps needs 2 slots, so the need for slots is put into the dialog stack. But then perhaps you want to go to another conversation and trigger another intent (example, you don't know how to fill the slots and you ask for help) so you expect that the chatbot triggers this dialog you asked for, and then return to the previous dialogs in the stack, so it will be returning to the fill slots state.
Also, an intent for cancel should be declared, but this is responsability of the person that trains the bot and not from the framework. The cancel intent expect to remove the last dialog form the dialog stack, so you return to the previous one.

This feature I think that needs more discussion before starting to implement it :) All help is welcome!

**Comment by jesus-seijas-sp** [comment]
Solved with https://github.com/axa-group/nlp.js/pull/45
