### ISSUE TITLE
Some random console.logs during execution - no option to switch logging off.

### ISSUE THREAD

**Issue by ppedziwiatr** [axa-group/nlp.js#1202]
**Describe the bug**
The library seems to console.log during the execution - with no option to switch off the logs completely.

**To Reproduce**
1. Run the example https://github.com/axa-group/nlp.js#example-of-use
2. A set of logs is being produced (without loggin level, time, etc - looks like console.log) - see 'screenshots'

**Expected behavior**
The library should not log anything to console by default. There should be an option to set the global logging level to sth like 'none'.

**Screenshots**
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/84311757/201623109-846d195a-786e-4ad2-82ac-cae1b10aa49b.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Package version: 4.24.0
 - Node version: 18.5

**Additional context**
The logger docs (https://github.com/axa-group/nlp.js/blob/master/docs/v4/logger.md) do not contain information about how to switch off the logging.

**Comment by jesus-seijas-sp** [comment]
https://github.com/axa-group/nlp.js#log-training-progress

```javascript
...
const manager = new NlpManager({ languages: ['en'], forceNER: true, nlu: { log: false }});
...
```

**Comment by ppedziwiatr** [comment]
Thanks! Didn't spot this in the docs, my fault :-)

Though I believe it should be switched-off by default.
