### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by PeterPilley** [axa-group/nlp.js#1204]
Hi guys, this is an awesome library is it still being worked on?

**Comment by aigloss** [comment]
Hi @PeterPilley ,

after some time of "more than low" activity, we are planning to retake the work on it. We'll probably start by cleaning up a little bit pull request and old issues, though.

**Comment by PeterPilley** [comment]
That is awesome news!!! I absolutely love nlp.js how can I help.

**Comment by meirpertzz** [comment]
Done

**Comment by Apollon77** [comment]
That's indeed wonderful news @aigloss. You should also have 2 emails from me offering help ... and in fact beside my open PRs I have several more stuff locally prepared but cannot make PRs because relies on the other PRs ...
