### ISSUE TITLE
Evaluator fails to walk a member with object expressions with an Identifier property

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#1225]
**Describe the bug**
Evaluator fails to walk a member with object expressions with an Identifier property

**To Reproduce**
```javascript
const { Evaluator } = require('@nlpjs/evaluator');

const evaluator = new Evaluator();

const script = `
obj[""+"x"].y;
({ a: 5, b: 7 })['a'];
({ a: 5, b: 7 })[n]
`;
const context = { obj: { x: { y: 555 } }, n: 'a' };
const answer = evaluator.evaluateAll(script, context);
console.log(answer); 
```
It shows in console ```[ 555, 5, undefined ]```

**Expected behavior**
It should show in console ```[555, 5, 5]```

**Additional context**
The walkMember should avoid the shortcut by property name and resolve the identifier by walk when the object type is ObjectExpression
Here:
https://github.com/axa-group/nlp.js/blob/master/packages/evaluator/src/evaluator.js#L182
And here:
https://github.com/axa-group/nlp.js/blob/master/packages/evaluator/src/javascript-compiler.js#L239

```javascript
 if (node.property.type === 'Identifier') {
      return obj[node.property.name];
    }
```

Should be:
```javascript
    if (node.property.type === 'Identifier' && node.object.type !== 'ObjectExpression') {
      return obj[node.property.name];
    }
```

**Comment by ericzon** [comment]
Thanks @jesus-seijas-sp , improvement applied in e11249fc3da79285c78c34a865fc37939eb0563b. We'll publish a version before ending this year.
