### ISSUE TITLE
NER - generalize learning to the whole entity

### ISSUE THREAD

**Issue by ilyub** [axa-group/nlp.js#1227]
**Is your feature request related to a problem? Please describe.**

Consider this sample:
```ts
manager.addNamedEntityText("human", "John", ["en"], ["John"]);
manager.addNamedEntityText("human", "Lucy", ["en"], ["Lucy"]);
manager.addDocument("en", "Hi, John", "say.hello");
manager.addDocument("en", "Hi, dog", "None");
manager.addDocument("en", "Hi, cat", "None");
const res1 = await manager.process("en", "Hi, John"); // -> say.hello
const res2 = await manager.process("en", "Hi, Lucy"); // -> None
```

I am getting "None" for Lucy.
But I would expect "say.hello" because "Hi, %human%" learned from "Hi, John" applies both to John and Lucy.

**Describe the solution you'd like**

Add 4th option to addDocument.
Let's call it "applyToEntity?: boolean".

When it is skipped everything works as is.
If it is added then learning done for one option should apply to all options from entity.

In our example, if skipped - apply only to John.
If applyToEntity=true, apply to all humans.

If this is somehow already possible please describe.

**Describe alternatives you've considered**

No

**Additional context**

No

**Comment by Apollon77** [comment]
Do you mean to use Enum values to automatically learn better? Then https://github.com/axa-group/nlp.js/pull/1220 should bring what you want. Or what exactly you mean?

(But you would need add one document with "Hello @name" :-) )

**Comment by Apollon77** [comment]
PS: maybe you would get better chances already now if you just add the mentioned document with "Hello @name" because then there should be a fallback try with enum contents ... try it
