### ISSUE TITLE
Not supporting for typescript

### ISSUE THREAD

**Issue by AruljothySundaramoorthy** [axa-group/nlp.js#1233]
I tried to install this in my NestJS , but it's throwing errors like 
Could not find a declaration file for module 'node-nlp'.

**Comment by aigloss** [comment]
Hi @AruljothySundaramoorthy,

this repository is not based on Typescript. If you need to import these packages into a Typescript project, you'll need to take care yourself of making them  "visible". 

Maybe this thread helps you on that: https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3
