### ISSUE TITLE
Starting a hobby project - Question 

### ISSUE THREAD

**Issue by levirtevs** [axa-group/nlp.js#1234]
first question - I saw this mentioned in the docs. How to set it up?
![nlp](https://user-images.githubusercontent.com/112684060/207355055-5667ab0e-9aa7-4852-a4a6-49976c1574e6.png)

second question - Idea of a system I thought and the last point in above picture are same. I think this system scales to even use nlp as a code parser. I want to build a code refactor tool using it.

**Comment by aigloss** [comment]
Hi @levirtevs ,

to use your custom language you should implement a Tokenizer, a Normalizer, a Stemmer, and a StopWords handler if needed. You can check any of the language packages, such as https://github.com/axa-group/nlp.js/tree/master/packages/lang-en, for examples.

**Comment by jesus-seijas-sp** [comment]
Only one comment...
Fantasy languages are supported, you don't need to implement Tokenizer, a Normalizer, or Stemmer.
There are unit tests showing how it's able to understand Klingon:
https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/packages/node-nlp/test/nlp/nlp-manager.test.js#L506

And how the trigrams for language guessing are automatically added, so the fantasy language is able to be recognized:
https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/packages/node-nlp/test/nlp/nlp-manager.test.js#L529

In fact, no need to be a fantasy language, can be a real language where we do not have implemented Tokenizer, a Normalizer, or Stemmer. Example: Vietnamese. Vietnamese is not officially supported by NLP.js, but when testing the accuracy of Amazon Massive, you get an outstanding accuracy with NLP.js, near the accuracy of huge models like XLM-R or mT5
