### ISSUE TITLE
Use mongodb for model.nlp

### ISSUE THREAD

**Issue by sbotalla88** [axa-group/nlp.js#1237]
I really like this lib for nlp in node.js. But I'd like to know if mongodb can be used for model.nlp. If not, can we please implement it?
Thanks!

**Comment by Apollon77** [comment]
You can define an own "filesystem" implememtation ... see https://github.com/axa-group/nlp.js/blob/master/docs/v4/core/file-system.md

So you just need to define the needed methods and then register this own instance as "fs" container

**Comment by ericzon** [comment]
MongoDB can be used, in fact, we have an @nlpjs/mongodb-adapter since 2 years ago. 
In the conf can be used with:
```
use: ['Basic', 'LangEn', 'Database', 'MongodbAdapter'...]
```

I hope it helps.
