### ISSUE TITLE
NPM packages maybe has a problem with inconsistent version codes

### ISSUE THREAD

**Issue by zmax** [axa-group/nlp.js#1240]
`@nlpjs/nlp` and `@nlpjs/nlg` that packages make me confuse. There may be a problem with inconsistent version codes.

The version numbers of the github repo and npm repo are the same, but the code is different.

Issue case: I'm trying to use a method called "registerActionFunction" in an npm package, but the method is not available.

**Comment by Apollon77** [comment]
In fact the versions are not bumbed on GitHub ... so in fact the code on nm is just "old" code, and GitHub is jewer and not yet released ...
