### ISSUE TITLE
Import/Export for classifier, without manager

### ISSUE THREAD

**Issue by DiegoRBaquero** [axa-group/nlp.js#137]
**Is your feature request related to a problem? Please describe.**
The import/export is only featured inside the NLP manager, but not for one classifier.

**Describe the solution you'd like**
Include the import/export functionality for a classifier

**Describe alternatives you've considered**
I currently do the process on my own, but this has broken before because of API changes between 2.3.0 and 2.3.1, where this was changed. (This should have been a major/breaking version)

**Additional context**

Currently, what I have to do this for one classifier only is: 

```js
      const classifier = new NlpClassifier({ language: 'es' })

      ...

      await classifier.train()

      const newModel = {}
      newModel.language = classifier.settings.language
      newModel.docs = classifier.docs
      newModel.features = classifier.features
      newModel.logistic = {}
      const { neuralClassifier } = classifier.settings
      if (neuralClassifier) {
        newModel.neuralClassifier = {}
        newModel.neuralClassifier.settings = neuralClassifier.settings
        newModel.neuralClassifier.classifierMap = {}
        Object.keys(neuralClassifier.classifierMap).forEach(key => {
          newModel.neuralClassifier.classifierMap[key] = deflate(
            neuralClassifier.classifierMap[key].toJSON()
          )
        })
      }
```

**Comment by maheshcv** [comment]
I too got this error after updating to the 2.3.1. It failed at node-nlp/lib/nlp/nlp-manager.js:551 (Does not seem to be able to access layers) during loading previous nlp model. I have tried to retrain and load but failed.

**Comment by jesus-seijas-sp** [comment]
Hello,

I just published version 2.3.2 that should solve this issue.

**Comment by maheshcv** [comment]
Great!! Thank you very much. It is working again

**Comment by jesus-seijas-sp** [comment]
Closing as confirmed as fixed
