### ISSUE TITLE
does not work dependence npm cjk-conv  

### ISSUE THREAD

**Issue by igornoriaqui** [axa-group/nlp.js#138]
does not work dependence npm cjk-conv  

to solve the problem. ..

/node_modules/cjk-conv/lib/zh/table/list.js
const __1 = require("../..");  // -----> add

//__1.default..
.concat(arr.map(w(__1.default.cjk2zht))) // add __1.default.
        // @ts-ignore
        .concat(arr.map(w(__1.default.cn2tw))) //add __1.default.
        // @ts-ignore
        .concat(arr.map(w(__1.default.cjk2zhs))) // add __1.default.
        // @ts-ignore
        .concat(arr.map(w(__1.default.cjk2jp))) //add __1.default.

**Comment by jesus-seijas-sp** [comment]
Closed as cjk-conv is no longer a dependency
