### ISSUE TITLE
Not the same behavior after a load

### ISSUE THREAD

**Issue by Klervix** [axa-group/nlp.js#139]
Hi there, and thank you for this great project!

**Describe the bug**
After a `load("./model.nlp")`, the result is not the same than after the training.

**To Reproduce**
Here is [the example](https://github.com/axa-group/nlp.js/blob/master/examples/console-bot) I used. I changed the `train-nlp.js` to add my own intents and utterances (the only changes I made).

- The first time I got this problem was with a big test: i trained 83 intents. It worked well just after the training. Then I restart the program - so I used the `load` function. After this, the result was always the same: the first trained intent, and a "NaN" score.

**node .\index.js**
**Program:** Trained (hr): Trained (hr): 358s 239.92041ms for 83 intents
**Program:** Say something!
**Me:** how are you
**Program:** smalltalk.greetings.how_are_you 0.4852741995322251
**node .\index.js**
**Program:** Say something!
**Me:** how are you
**Program:** smalltalk.agent.acquaintance NaN
**Me:** i should go to sleep
**Program:** smalltalk.agent.acquaintance NaN

- So I tried with less intents and it works better. But here is another problem I got:

**node .\index.js**
**Program:** Trained (hr): 249s 708.56ms for 56 intents
**Program:** Say something!
**Me:** how are you
**Program:** smalltalk.greetings.how_are_you 0.4852741995322251
**node .\index.js**
**Program:** Say something!
**Me:** are you ok
**Program:** smalltalk.agent.there 0.34087913613429177
**Me:** are you fine
**Program:** smalltalk.appraisal.good 0.41805671303445147
**Me:** how are you
**Program:** smalltalk.agent.there 0.2816300128888281
**Me:** how are you
**Program:** smalltalk.agent.there 0.2816300128888281
**node .\index.js**
**Program:** Say something!
**Me:** how are you
**Program:** smalltalk.agent.there 0.2816300128888281

Is there a solution to have the same results everywhere? My results were much better just after the training than after loading... Maybe I'm not using it correctly!

Thank you! :)

**Comment by NadherBB** [comment]
Hi Klervix, I faced the same issue too, the loading or importing does not work anymore with version 2.3.1.
A solution is to downgrade the version you'r using.
That would be great to fix this issue on the next version.

**Comment by obaid** [comment]
I had the same issue and downgrading back to 2.2.4 resolved it. 2.3.0 is also not generating proper results for me.

**Comment by Klervix** [comment]
Thank you for your advices! 
@obaid you're right it works with this version :)

**Comment by jesus-seijas-sp** [comment]
Hello,
I just published 2.3.2 that should solve that.

**Comment by revolunet** [comment]
closable ?

**Comment by jesus-seijas-sp** [comment]
Yes, closable :)
