### ISSUE TITLE
Add random answers to manager.addAnswer

### ISSUE THREAD

**Issue by ran-j** [axa-group/nlp.js#140]
Add random answers to manager.addAnswer.

**Describe the solution you'd like**
It would be nice to add random response for training, ex:
```
manager.addDocument('en', 'I have to go', 'greeting.bye');
manager.addAnswerRandom('en', 'greeting.bye', ['Till next time, {{name}}!','see you, {{name}}!']);
```
and then the function return just one answer.

**Comment by jesus-seijas-sp** [comment]
Hello, I'm closing this. With addAnswer you can add several answer, and one will be chosen at random when the intent is triggered.
