### ISSUE TITLE
Context not working

### ISSUE THREAD

**Issue by ran-j** [axa-group/nlp.js#141]
**Describe the bug**
Context is not working, I try the example code.

https://imgur.com/a/zMV3gow

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Node 8,12 -- nlp.js latest

**Comment by Nahdus** [comment]
I think you are expected to add named entity.

```
const { NlpManager, ConversationContext } = require('node-nlp');

const manager = new NlpManager({ languages: ['en'] });
const context = new ConversationContext();


manager.addDocument('en', 'Hello my name is %name%', 'greeting.hello');
manager.addDocument('en', 'I have to go', 'greeting.bye');
manager.addAnswer('en', 'greeting.hello', 'Hey there!');
manager.addAnswer('en', 'greeting.bye', 'Till next time, {{name}}!');


manager.addNamedEntityText(
  'name',
  'John',
  ['en'],
  ['john', 'John'], 
  );


manager.train()
  .then(async result => {
    r = await manager.process('en', 'Hello my name is John', context)
    console.log(context)
    return r
  })
  .then(async result => await manager.process('en', 'I have to go', context)
    )
  .then(result => {
       console.log(result.answer)
  })
```

**Comment by ran-j** [comment]
Please update the docs then

**Comment by danbulant** [comment]
@Nahdus This isn't the case. The context worked for me, and also you (propably) don't want to add all names in the named entity.

**Comment by DesiKeki** [comment]
@danbulant How does it work? Is there anything else we need to do other than what is shown in the example in docs? With the code given in docs example, it doesn't work for me too.
