### ISSUE TITLE
MultiLanguage Support for NlpManager behaviour not correct

### ISSUE THREAD

**Issue by ChintanPania** [axa-group/nlp.js#144]
**Describe the bug**
When we create a new NlpManager and providing multiple languages settings, it is not able to recognize the language within the same intent.

**To Reproduce**
1. Below is the code to reproduce the issue,
const { NlpManager } = require("node-nlp");

async function main() {
  const manager = new NlpManager({ languages: ['en', 'de'] });

  manager.addDocument('en', 'hello', 'greet');
  manager.addDocument('de', 'hallo', 'greet');  
  
  await manager.train();
  manager.process('Hallo').then(console.log);
}

main();

**Expected behavior**
The word 'Hallo' should come as Greet intent with Language as German, instead it comes as English.

**Screenshots**
![image](https://user-images.githubusercontent.com/25343448/51890884-69ac3880-23c3-11e9-8867-eb74a0c17af5.png)

**Comment by ChintanPania** [comment]
Thanks @jesus-seijas-sp for the clarification.

The actual issue i have is integration with Microsoft Bot v4, where i'm training both English and German data, but the German Utterance is not classified after the training, please do guide me here or suggest an approach.

Thanks

**Comment by jesus-seijas-sp** [comment]
Solved in 3.x
