### ISSUE TITLE
novel-segment Error

### ISSUE THREAD

**Issue by machester4** [axa-group/nlp.js#149]
**Describe the bug**

**To Reproduce**
1. Run console example

![captura de pantalla 2019-02-18 a la s 21 20 52](https://user-images.githubusercontent.com/25928946/52982141-1d04bd80-33c3-11e9-8717-d79bb2f902bc.png)

**Comment by jesus-seijas-sp** [comment]
Hi,

I just tried to reproduce this error. Is funny, but I got it reproduced in runkit minutes ago, but right now is working, so I have 2 virtual machines with exactly the same code, but the old one is failing and the new one is working.

It recommend you to remove node_modules and install again, because could be some issue related to npm.

**Comment by machester4** [comment]
hello, I'm using yarn and try deleting node_modules, yarn.lock but I did not succeed

**Comment by machester4** [comment]
try using only NPM and it is working. thx @jesus-seijas-sp

**Comment by erenaud3** [comment]
Hi ! I think this error comes from a recent update in [node-segment-dict package](https://github.com/bluelovers/node-segment-dict) (two days ago).

I got your code working by commenting the declaration of chinese tokenizer and stemmers in lib/nlp/nlp-util.js (l.28)
```
	const BasqueStemmer = require('./stemmers/basque-stemmer');
	const CatalanStemmer = require('./stemmers/catalan-stemmer');
	const CzechStemmer = require('./stemmers/czech-stemmer');
	// const ChineseStemmer = require('./stemmers/chinese-stemmer');
	// const ChineseTokenizer = require('./tokenizers/chinese-tokenizer');
	const DanishStemmer = require('./stemmers/danish-stemmer');
	const DutchStemmer = require('./stemmers/dutch-stemmer');
	const EnglishStemmer = require('./stemmers/english-stemmer');
```

**Comment by jesus-seijas-sp** [comment]
I had change the code so the nove-segment library is lazy-loaded, only if chinese is used. I expect that the people of novel-segment handle this issue soon, otherwise I'll have to find a workaround.

**Comment by jesus-seijas-sp** [comment]
Closing as novel-segment is no longer a dependency
