### ISSUE TITLE
Full japanese support

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#16]
**Is your feature request related to a problem? Please describe.**
Japanese currently right now only works with katakana, beacause the Natural stemmer only supports katakana.

**Describe the solution you'd like**
Support Katakana, Hiragana and Joyo Kanji, perhaps it can be achieve with a Kanji -> hiragana -> katakana translation.

**Describe alternatives you've considered**
Doing a complete stemming on hiragana and katakana. Synonims over Kanji. Translate to base romanji.

**Comment by loretoparisi** [comment]
👍 That would be awesome. I would suggest for transliteration [kakasi.js](https://github.com/loretoparisi/kakasi.js) that is based on kakasi binaries and support therefore all [kakasi](https://github.com/loretoparisi/kakasi) features.

**Comment by jesus-seijas-sp** [comment]
Support for japanese done with built-in entity extraction
