### ISSUE TITLE
language guesser doesn't work well

### ISSUE THREAD

**Issue by gitawego** [axa-group/nlp.js#161]
**Describe the bug**
some basic words can't be guessed correctly
**To Reproduce**
```js
const {Language} = require('node-nlp');

const language = new Language();
const guess = language.guess(
  'hello'
);
console.log(guess[0]);

```

**Expected behavior**

'hello' shouldn't be guessed as Sotho, but English. same for the French word "bonjour" is guessed as Lingala.

plus, I've already defined document for hello, but it's still guessed as Sotho. 

```js
manager.addDocument('en', 'hello', 'greetings.hello');
```

**the language guesser should first search in currently defined documents to increase precision.**

**Comment by jesus-seijas-sp** [comment]
Hello!
The language guesser that we use is franc: https://github.com/wooorm/franc

You can reproduce the bug only using franc:
```javascript
const franc = require("franc");
const guess = franc.all("hello", { minLength: 5 });
console.log(guess);
```

The minLength parameter is filled with the length of the utterance when is lower than 10.
Usually you don't use the language guesser with so short utterances, and also a whitelist is automatically provided with the languages of the NlpManager.

**Comment by jesus-seijas-sp** [comment]
Hello again!

Even with that I tested with an small sample with "hello" in english and "bonjour" in french, and is true that is identified wrong as french:

```javascript
const { NlpManager } = require("node-nlp");

const manager = new NlpManager({ languages: ['en', 'fr'] });
manager.addDocument('en', 'hello', 'greetings.hello');
manager.addDocument('fr', 'bonjour', 'greetings.hello');

(async() => {
  await manager.train();
  manager.save();
  const response = await manager.process('hello');
  console.log(response);
})();
```

So, I see that for small utterances another solution should be done before passing to franc, example checking the features (words) present in each language in the classifiers.

**Comment by gitawego** [comment]
or maybe before passing to franc, check if there is any match in document definitions.  what surprised us is we have already defined the phrase as u did
```js
manager.addDocument('en', 'hello', 'greetings.hello');
```
but when processing the "hello", it takes a lot of time and returns french (in our case)

**Comment by jesus-seijas-sp** [comment]
Hello @gitawego 
The Language Guesser in the version 3.0.1 now is able to learn from the utterances used to train. Basically it extracts the trigrams from the utterances of each language, and add them to the trigrams used to identify languages, so right now hello is working well.
It also allows to identify languages that does not exists. Example: if you use a training in klingon, it will learn to identify klingon utterances.

**Comment by gitawego** [comment]
thanks a lot, will try it

**Comment by jesus-seijas-sp** [comment]
Hello @gitawego Did you tried it? Can we close the issue?

**Comment by gitawego** [comment]
it works now. thanks a lot
