### ISSUE TITLE
addNamedEntityText is not working 

### ISSUE THREAD

**Issue by snyuryev** [axa-group/nlp.js#171]
Hi!

I'm trying to recreate the first example from this documents (https://github.com/axa-group/nlp.js/blob/a3c9a6599957a7f360a598434226bc8f2999128b/docs/nlp-manager.md) with Russian language. And "entities" (such as %hero% and %food%) are not recognised and not returned with result of process(). 

It works fine with English, but not with Russian language. Is it supported only for English?

**Comment by jesus-seijas-sp** [comment]
Hello, the problem was that the isAlphanumeric function in similar search worked only with latin charset. Now is fixed to work with all kind of charsets. Version 3.0.2 published with the fix.

**Comment by snyuryev** [comment]
@jesus-seijas-sp thanks for response! will try it and come back with result.

**Comment by snyuryev** [comment]
Confirm that is working now with 3.0.2
Thank you!
