### ISSUE TITLE
Crop "e" in model 

### ISSUE THREAD

**Issue by jechazelle** [axa-group/nlp.js#176]
Hi !
I use the nlpManager (with nlp.js 3.0.2) :

`const nlpManagerFr  = new NlpManager({languages: ['fr']});`

and if I inspect my model.nlp, some letters are crops :

```
              {
                "intent": "[BOOK] time.to.read",
                "utterance": [
                  "temp",
                  "pour",
                  "lir",
                  "book"
                ],
                "tokens": [
                  "temp",
                  "pour",
                  "lir",
                  "book"
                ]
              },
```
lire => lir
temps => temp

How can I get all word in the model to up the performance please ?

I tried to use this on my manager (https://github.com/axa-group/nlp.js/issues/160) :
```
const classifier = manager.classifiers['fr'];
classifier.settings.keepStopWords = false;
```
but I have an error : 

> TypeError: Cannot read property 'fr' of undefined

Thank you for Nlp.js, awesome library ! 👍

**Comment by jesus-seijas-sp** [comment]
Hello! 
This is normal, is called "stem". It is one NLP technique to calculate the root of words so the models does not have to be trained with all the verb forms or derivated words.
Example:
- Who is your developer
- Who developed you
- Who is doing your development
- Who is developing you

These four utterances means the same, but if you train only with one tokenizing the words, you'll find that developer !== developed !== development !== developing

That means that if an stemmer is not used, then all derivated words and verb forms must be used for training so the chatbot has the best score... and this is not only time consuming, but also means to have so many features for the neural network.

Is not perfect, the perfect way is to calculate the lemma, but this process uses huge dictionaries. Example of how stemmer works with conjugations of lis verb:
lire => lir
lis => lis
lit => lit
lisons => lison
lisez => lis
lisent => lisent
lisais => lis
lisait => lis
lisions => lision
lisiez => lis

You can see that stemmer improves the score of NLU in this article: https://medium.com/@jseijas/how-to-build-your-own-nlp-for-chatbots-9b4c08eb03a9 (search stemmer). Using the SIGDIAL22 corpora, without stemmer the score is 0.90, with stemmer is 0.92.

**Comment by jechazelle** [comment]
Thank you for the article and your answer @jesus-seijas-sp ! 👍
