### ISSUE TITLE
How about Slot Filling with NLU ?

### ISSUE THREAD

**Issue by G33kLabs** [axa-group/nlp.js#179]
Version 3 is really fast !!
Are you planning to add slot filling in NLU manager as NLP ?

**Comment by jesus-seijas-sp** [comment]
Well, is not yet in the pipeline, as is already in the NLPManager, and well, Slot Filling needs the context and NER, that are at NLP level.

Currently in the pipeline I have the development of a Model Analyzer, a tool to identify the potential issues of a model, and find how to tweek it to perform better.

**Comment by G33kLabs** [comment]
Thanks ! I'll use NER after each NLU classification for defined entities and NLP for variable slots.

**Comment by jesus-seijas-sp** [comment]
Hello @G33kLabs,
If you need some help in the implementation, or you have suggestions, feel free to contact me by email!
On the other hand, are you using NLP.js already in your tech or still evaluating it?

Thank you!

**Comment by G33kLabs** [comment]
I will @jesus-seijas-sp :) I'm preparing unit tests with a lot of intents.
Currently I'm using NLP.js on our robots for voice interactions with humans, it's in french, but you can see a demonstration here : https://www.youtube.com/watch?v=IKY21OEforw
