### ISSUE TITLE
Any example for how to train the "datetime" entity for another longuage

### ISSUE THREAD

**Issue by obiwankenoobi** [axa-group/nlp.js#181]
I would like to train the model to recognise other languages. Especially the  "datetime" entity. For example to be able to recognise day names in Hebrew.

There is an API for that? Or How may I approach to it? 

Thank you!

**Comment by jesus-seijas-sp** [comment]
Hello @obiwankenoobi 
Now we integrate with Duckling, that includes a lot of languages. If your language is not supported by Ducling, you can follow their instructions to add a new language.

**Comment by jesus-seijas-sp** [comment]
Closing as solved
