### ISSUE TITLE
"TypeError: utterance.slice is not a function" in DomainManager.generateStemKey

### ISSUE THREAD

**Issue by alex-rddi** [axa-group/nlp.js#184]
**Describe the bug**

Unexpected TypeError inside a promise when calling the NlpManager.process function.
The code runs fine on some training datasets with up to 127 intents but crashes when tested with different datasets with 382 and 390 intents.

The function seems to return results at first but then crashes at some point when a specific record is sent.

```
(node:24684) UnhandledPromiseRejectionWarning: TypeError: utterance.slice is not a function
    at DomainManager.generateStemKey (/home/ubuntu/nlpsjs/node_modules/node-nlp/lib/nlu/domain-manager.js:80:8)
    at DomainManager.getClassifications (/home/ubuntu/nlpsjs/node_modules/node-nlp/lib/nlu/domain-manager.js:188:28)
    at NluManager.getClassifications (/home/ubuntu/nlpsjs/node_modules/node-nlp/lib/nlu/nlu-manager.js:277:36)
    at NlpManager.process (/home/ubuntu/nlpsjs/node_modules/node-nlp/lib/nlp/nlp-manager.js:362:34)
    at Engine.test (/home/ubuntu/nlpsjs/Engine.js:49:45)
```

**To Reproduce**
I'm using this code to get results from the NlpManager once it is trained
```javascript
      for (const record of records) {
        const response = await this.manager.process('fr', record.verbatim);
        // where records looks like
        /*
        "records": [
        {
          "entities": [],
          "verbatim": "Comment accéder à mon compte"
        },
        {
          "entities": [],
          "verbatim": "comment fair e pour accéder à mon compte sur internet ?"
        },
        {
          "entities": [],
          "verbatim": "Mon compte client"
        }
        ]
        */
        // [...]
      }
```

And this is the code I have for the training:
```javascript
class Engine {
  constructor(trainFile, testFile, version) {
    this.version = version;
    this.manager = new NlpManager({ languages: ['fr'] });
    this.trainData = require(trainFile);
    this.testData = require(testFile);
    this.results = {};
  }

  async train() {
    for (const intentName in this.trainData.intents) {
      const { records } = this.trainData.intents[intentName];
      console.log(intentName, records.length);

      for (const record of records) {
        this.manager.addDocument('fr', record.verbatim, intentName);
      }
    }

    await this.manager.train();
    this.manager.save();
  }
```
**Expected behavior**
Expect the process function to return a response.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Version Node v8.11.1 / node-nlp v3.1.1

**Comment by jesus-seijas-sp** [comment]
Hello:

![image](https://user-images.githubusercontent.com/15154218/57294208-36b2c880-70c7-11e9-808b-d760aa7a8a96.png)

This is called just after doing the stemming. If slice() does not exists, then the stems object is not an array.

![image](https://user-images.githubusercontent.com/15154218/57294276-6366e000-70c7-11e9-861c-36486e8184e0.png)

As the tokenizeAndStem of the stemers starts with an empy array and at least return it, it looks like you're providing an utterance that is not an string neither an array, perhaps null, undefined or an object.

Can you provide the utterance that is causing the error?

**Comment by alex-rddi** [comment]
Hi @jesus-seijas-sp 
Thanks for your reply, actually I had a look at what utterance is causing the error, and it is 0 (the number 0). I haven't looked the typeof, but my code is parsing JSON to get this, so it probably send it to the process function as a number rather than a string, that would explain the error. I'm gonna adjust my code to make sure it sends the 0 as a string.

Thanks for your help.

**Comment by alex-rddi** [comment]
Closing this issue, adding .toString() to make sure that the parameter passed to the process function solves it.

In the future, it could be nice for the process function to throw an error if the utterance given hasn't got the right type. 

Thanks for your help @jesus-seijas-sp 
And by the way, this is a really impressive piece of work!
