### ISSUE TITLE
Example for using Slot Filling independent of Microsoft Bot Framework

### ISSUE THREAD

**Issue by Immortalin** [axa-group/nlp.js#187]
For e.g. frontend browser only bots etc. with no server backend.

**Comment by Aliyss** [comment]
@Immortalin Hey there did you find a solution. I was wondering the same thing.

**Comment by Immortalin** [comment]
I didn't. Instead I just did everything client side without the bot framework.

**Comment by Apollon77** [comment]
Docs for v4 added in #1171
