### ISSUE TITLE
wildcard regexp

### ISSUE THREAD

**Issue by francescoagati** [axa-group/nlp.js#19]
hi,
**Is your feature request related to a problem? Please describe.**
can be possible use addRegexEntity in manager for create a wildcard?

**Comment by jesus-seijas-sp** [comment]
Hello! 
May you provide an example of what you want to achieve? To understand it better.
Thank you!

**Comment by francescoagati** [comment]
for example i would like match this 
``` i want go from %departure to %destination```
where %departure and %destination can be any string or words

**Comment by franher** [comment]
Hello @francescoagati maybe you are asking for https://github.com/axa-group/nlp.js/issues/12 ? I know @jesus-seijas-sp is working on this slot filling feature.

**Comment by francescoagati** [comment]
yes this thanks
