### ISSUE TITLE
Removing Named Entity

### ISSUE THREAD

**Issue by rayeeskm** [axa-group/nlp.js#190]
Is it possible to dynamically remove an already added named entity from the NerManager?

Like i added "subscriber" as a named entity, but over time, app doesn't need it to be considered a named entity anymore, Is it possible to do this dynamically , without changing the code and then restarting the app?

**Comment by jesus-seijas-sp** [comment]
Hello, the NerManager has methods to remove texts from a named entity:
https://github.com/axa-group/nlp.js/blob/master/lib/ner/ner-manager.js#L212
Or to remove a Named Entity:
https://github.com/axa-group/nlp.js/blob/master/lib/ner/ner-manager.js#L189

**Comment by jesus-seijas-sp** [comment]
Closing as it was solved
