### ISSUE TITLE
Not recognizing intent

### ISSUE THREAD

**Issue by Loganrose** [axa-group/nlp.js#195]
The classifier is not recognizing certain intents due to a user input of a random number or ID. If i were to say something like `kick` it would recognize the intent but if i were to say `kick <insert random id>` it wouldn't.

**Comment by jseijas** [comment]
Hi, I'm travelling without laptop, but I tested it with my mobile phone using runkit... 
I used this code and works perfectly. Can you share your code to identify whats happening to you?


```javascript
const { NlpManager } = require("node-nlp");

async function main() {
  const manager = new NlpManager({ languages: ['en']});
  manager.addDocument('en', 'kick', 'kick');
  manager.addDocument('en', 'push', 'push');
  await manager.train();
  const result = await manager.process('kick 7');
  console.log(result);
}

main();
```

**Comment by Loganrose** [comment]
Well sure its gonna work if you use only 1 digit behind kick. It works just fine when i do `kick` but when i do `kick 145749360515219456` it doesn't work.

**Comment by jseijas** [comment]
Teste it with your id, works perfect with exctly the same score (0.99).

NLP.js does not uses LSTM so it don't goes char by char. It goes word by word so length of the word does not matters. More on that, words not used during training are not fetures so are discarded for clasification.

So please try the code that I provided or share your code.

**Comment by Loganrose** [comment]
So i think I've isolated the issue. I load my intents in from a database (nedb). It's kind of strange though because other intents and things work. I am only having an issue from this one
