### ISSUE TITLE
Slot filling is broken

### ISSUE THREAD

**Issue by imcosta** [axa-group/nlp.js#197]
Hello! I'm having problems with Slot Filling. I tried [this example](https://github.com/axa-group/nlp.js/blob/master/docs/slot-filling.md#entities-with-the-same-name) but It's seems broken.

**My console**
> node demo.js
Who did you see?
Who did you see?
Who did you see?
Who did you see?
Who did you see?

**Expected behavior**
  // Console output:
  // Wow! You saw spiderman and iron man eating pasta!
  // With whom did you see iron man?
  // With whom did you see thor?
  // What where they eating?
  // Who did you see?

Node v11.15.0.

**Comment by jseijas** [comment]
Hello!!! This is because the new code is merged to master but not published as version yet.... I will publish June 20 when I return from holidays

**Comment by imcosta** [comment]
Thank you! Have a nice holidays. :)

**Comment by obaid** [comment]
@jseijas This issue still persists in master. Checkout #242 for details.
