### ISSUE TITLE
Wild card match on utterance?

### ISSUE THREAD

**Issue by obaid** [axa-group/nlp.js#205]
Can a utterance in addDocument be a regular expression? 

For example;

I want to go to an intent “save email” if the utterance is a valid email. Currently, the entity is extracted properly but the intent is “None”

**Comment by jesus-seijas-sp** [comment]
Hello,
You cannot use a regular expression as utterance, but you can use a regular expression as entity and then use the entity in the utterance. It was not working (saw your other issue) but now is fixed in https://github.com/axa-group/nlp.js/pull/208

**Comment by obaid** [comment]
Thank you @jesus-seijas-sp :)
