### ISSUE TITLE
Train update

### ISSUE THREAD

**Issue by ran-j** [axa-group/nlp.js#214]
**Is your feature request related to a problem? Please describe.**
When train a big amount of data the train leaves you in the dark

**Describe the solution you'd like**
A optional callback to display information about the training like tensorflow JS.

**Comment by jesus-seijas-sp** [comment]
Added train update in version 3.2.1

You can use this api passing a true and will log in console:
```javascript
const manager = new NlpManager({ languages: ['en'], nlu: { log: true } });
```

or providing a function:
```javascript
const logfn = (status, time) => console.log(status, time);
const nlpManager = new NlpManager({ languages: ['en'], nlu: { log: logfn } });
```

**Comment by ran-j** [comment]
Nice one
