### ISSUE TITLE
Sentiment Analysis in Portuguese 

### ISSUE THREAD

**Issue by ran-j** [axa-group/nlp.js#218]
To get sentiment analysis in portuguese is just translated the files in sentiment/languages" ?.
if yes , if I do it you can add to this project ?

**Comment by jesus-seijas-sp** [comment]
Hello, you have good examples of the data for sentiment analysis at https://github.com/axa-group/nlp.js/tree/master/lib/sentiment/languages

You can choose one format (AFINN, Senticon, Pattern) and translate it. And do a PR.

**Comment by ran-j** [comment]
ok
