### ISSUE TITLE
Make process asynchronous

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#22]
**Is your feature request related to a problem? Please describe.**
As we want to open the development to integration with APIs, example Duckling in the issue https://github.com/axa-group/nlp.js/issues/15 , the process method must be asynchronous, while currently is synchronous.

**Describe the solution you'd like**
- NerManager findEntities must return a Promise.
- NlpManager process must return a Promise.
- Recognizer recognizeUtterance and recognize must change to use NlpManger process as a promise
- All the tests involving NerManager, NlpManager and Recognizer must change to handle async.

Async/await is welcome to have better syntax.
Another approach is to have NerManager.findEntities and NlpManger.process with versions Sync and Async (following node standards, only the sync version should have the suffix).

**Comment by vvscode** [comment]
@jesus-seijas-sp  except changing an interface - nothing else should be changed? right?

**Comment by jesus-seijas-sp** [comment]
@vvscode Correct. The problem is that is a breaking change so it will mean a major version, an also affect to so many tests.
The idea is that the interface must be prepared so the ner-manager instead of using microsoft recognizer that is sync, can use call to apis like duckling.

**Comment by vvscode** [comment]
I'm taking it

**Comment by DiegoRBaquero** [comment]
I would like to point out that even if using async/await, train method blocks completely the event loop. In my API server, requests stop being received until training is done
