### ISSUE TITLE
BaseStemmer has too many dependencies

### ISSUE THREAD

**Issue by dpinol** [axa-group/nlp.js#225]
**Describe the bug**
BaseStemmer.js imports all tokenizers, when it only needs TreebankWordTokenizer. Some of the tokenizers, like Japanese & Chinese, has special requirements . 

**To Reproduce**
In my typescript project I get the errors below when importing BaseStemmer.js

**Expected behavior**
There should be a way to import Vasque and Catalan stemmers without importing all tokenizers.

**Additional context**
I created a PR to solve it https://github.com/axa-group/nlp.js/pull/224

```
   WARNING in my_project/node_modules/segment-dict/lib/loader/index.js 11:11-68
    Critical dependency: the request of a dependency is an expression
     @ my_project/node_modules/segment-dict/index.js
     @ my_project/node_modules/novel-segment/index.js
     @ my_project/node_modules/node-nlp/lib/nlp/tokenizers/chinese-tokenizer.js
     @ my_project/node_modules/node-nlp/lib/nlp/tokenizers/index.js
     @ my_project/node_modules/node-nlp/lib/nlp/stemmers/base-stemmer.js

   WARNING in my_project/node_modules/novel-segment/lib/submod/ChsNameOptimizer.d.ts 12:7
    Module parse failed: Unexpected token (12:7)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |  * @todo 支援 XX氏
    |  */
    > export declare class ChsNameOptimizer extends SubSModuleOptimizer {
    |     protected _TABLE: IDICT<IWord>;
    |     name: string;
     @ my_project/node_modules/novel-segment/lib/submod sync ^\.\/.*$ ./ChsNameOptimizer.d.ts
     @ my_project/node_modules/novel-segment/lib/segment/methods/useModules2.js
     @ my_project/node_modules/novel-segment/lib/Segment.js
     @ my_project/node_modules/novel-segment/index.js
     @ my_project/node_modules/node-nlp/lib/nlp/tokenizers/chinese-tokenizer.js
     @ my_project/node_modules/node-nlp/lib/nlp/tokenizers/index.js
     @ my_project/node_modules/node-nlp/lib/nlp/stemmers/base-stemmer.js
```

**Comment by jesus-seijas-sp** [comment]
Hello!
That's true, I use too much the deconstructing ES6 way to import, even when are internal dependencies, I didn't taked into account the potential impact on transpilers. I will merge the PR.

On the other hand, if you are interested on a little workshop around nlp.js, contact me by mail, it seems that we are neighbors.

**Comment by jesus-seijas-sp** [comment]
Now it's all splitted into small pieces in the version 4, so this is no longer applicable.
