### ISSUE TITLE
Understanding how to structure my app given available features...

### ISSUE THREAD

**Issue by liamlows** [axa-group/nlp.js#234]
# Issue Template

## Summary

First off, I apologize if I am asking this question in the wrong place. I couldn't find what I was looking for in the docs and figured this is the next best place to ask!

Currently, I am using NLP.JS to construct an application that aids users in searching for frequently asked questions by providing an answer directly in the search results of the website. For example, if someone were to search "What is the office wifi password?" or "How do I clock my hours worked?" then the application (using trained data on such queries & with stopword removal) will respond with an appropriate answer directly in the search results. I have currently constructed a model that uses one NLPManager object which contains several queries (with stopword removal) across various topics. There are 14 topics and each topic may have as little as 9 queries or as many as 120 (total of 801, mean of ~57). When a user enters a search, the application NLPManager will classify based off that model. 

My question to you guys is how could the number of false positives (responds with an answer when the question asked does not fall in line with said answer or any answer) be reduced? Stopword removal has proved to be very useful with this issue however, I'd still like to improve the accuracy if I can. Also, I have been trying to refine the training data to contain less general words/sentences and that has seemed to help too. Are there available features I am not make use of? Is what I am already doing the best I can do?

Thanks guys!

## Simplest Example to Reproduce

N/A

## Expected Behavior

N/A

## Current Behavior

N/A

## Possible Solution

- stopword removal?
- domain specification?

## Context

N/A

## Your Environment

ExpressJS server running on Node.JS, local development 

| Software             | Version |
|----------------------|---------|
| `nlp.js`   |    3.1.1     |
| `node`               |    10.16.0     |
| `npm`                |    6.9.0     |
| Operating System     |    MAC OS X 10.14.6     |

**Comment by jesus-seijas-sp** [comment]
Hello, I see that you're using the version 3.1.1.
The main objective of the version 3.4 (current one) was to reduce false positives. So please give a try to version 3.4, and then provide feedback!
Thank you!

**Comment by liamlows** [comment]
@jesus-seijas-sp Awesome, Thanks for letting me know! I went ahead and updated and it is very clear that some work was done and it looks great so far! Right now it rarely identifies false positives but my model had to be tweaked a bit in order to get desirable results and now it working great!

I'm going to go ahead and close the issue but I was just curious, what are the best ways to improve the model? Does it like having lots and lots of data? Maybe splitting up the models or trying different methods of classification? I have a fairly small data set (now down to 509 terms across 13 topics) so I am trying to see other ways to help improve accuracy other than throwing in more data.

Great job on the update though guys! Love the work you guys are doing and have done!
