### ISSUE TITLE
Supporting emotions?

### ISSUE THREAD

**Issue by obaid** [axa-group/nlp.js#236]
Can't seem to get emoticons to work as an input. I am sure I am doing something incorrect with the setup.

```js
manager.addDocument("en", "😀", "smile");
manager.addDocument("en", "🐵", "monkey");
manager.train().then(() => {
     manager.process('en', '😀').then(result => console.log(result.intent));
})

I always get 'monkey' as the intent.

**Comment by jesus-seijas-sp** [comment]
Solved by https://github.com/axa-group/nlp.js/pull/237

**Comment by obaid** [comment]
Thanks @jesus-seijas-sp! This is awesome. I was thinking yesterday on how to approach this and you have beaten me to the punch. :)
