### ISSUE TITLE
unable to implement Example of use

### ISSUE THREAD

**Issue by Nahdus** [axa-group/nlp.js#245]
the code below
```
const { NlpManager } = require('node-nlp');

const manager = new NlpManager({ languages: ['en'] });
// Adds the utterances and intents for the NLP
manager.addDocument('en', 'goodbye for now', 'greetings.bye');
manager.addDocument('en', 'bye bye take care', 'greetings.bye');
manager.addDocument('en', 'okay see you later', 'greetings.bye');
manager.addDocument('en', 'bye for now', 'greetings.bye');
manager.addDocument('en', 'i must go', 'greetings.bye');
manager.addDocument('en', 'hello', 'greetings.hello');
manager.addDocument('en', 'hi', 'greetings.hello');
manager.addDocument('en', 'howdy', 'greetings.hello');

// Train also the NLG
manager.addAnswer('en', 'greetings.bye', 'Till next time');
manager.addAnswer('en', 'greetings.bye', 'see you soon!');
manager.addAnswer('en', 'greetings.hello', 'Hey there!');
manager.addAnswer('en', 'greetings.hello', 'Greetings!');

// Train and save the model.
(async() => {
    await manager.train();
    manager.save();
    const response = await manager.process('en', 'I should go now');
    console.log(response);
})();
```
does not produce any console log

Tried debugging, the code abruptly stops at await manager.train();

**Comment by jesus-seijas-sp** [comment]
Perhaps you can give more info about: SO version, node version node-nlp version.

**Comment by jesus-seijas-sp** [comment]
By the way, you can execute it online in runkit... https://runkit.com/jesus-seijas-sp/5d62a6dea45f75001ac4a485

**Comment by Nahdus** [comment]
the version i am using is 
"node-nlp": "^2.3.0"

this is the code snippet found within \node_modules\node-nlp\lib\nlp\nlp-manager.js

 /**
   * Train the classifiers for the provided locales. If no locale is
   * provided, then retrain all the classifiers.
   * @param {String[]} locale List of locales for being retrained.
   */
  ```
async train(locale) {
    let languages;
    if (locale) {
      languages = Array.isArray(locale) ? locale : [locale];
    } else {
      ({ languages } = this);
    }
    await Promise.all(
      languages.map(async language => {
        const truncated = NlpUtil.getTruncatedLocale(language);
        const classifier = this.classifiers[truncated];
        if (classifier) {
          await classifier.train();
        }
      })
    );
    
  }
```
noticed the latest version has this
```
/**
   * Train the classifiers for the provided locales. If no locale is
   * provided, then retrain all the classifiers.
   * @param {String[]} locale List of locales for being retrained.
   */
  async train(languages) {
    return this.nluManager.train(languages);
  }
```

and version 2.5.2 has

```
/**
   * Train the classifiers for the provided locales. If no locale is
   * provided, then retrain all the classifiers.
   * @param {String[]} locale List of locales for being retrained.
   */
  async train(locale) {
    let languages;
    if (locale) {
      languages = Array.isArray(locale) ? locale : [locale];
    } else {
      ({ languages } = this);
    }
    return Promise.all(
      languages.map(async language => {
        const truncated = NlpUtil.getTruncatedLocale(language);
        const classifier = this.classifiers[truncated];
        if (classifier) {
          await classifier.train();
        }
      })
    );
  }
```

**Comment by jesus-seijas-sp** [comment]
Only a question, if you're starting with the first snippet, why a so old version of the code?
I mean, the API has changed over the time, and so the documentation, so the snippet you're trying works with the current version, but of course don't works with 2.3.x (tested with runkit).

**Comment by Nahdus** [comment]
okay, Thanks for the reply.

I was building a chat app around node-nlp core and left it untouched since around 5 months ago.
now when I re-ran the tests. everything seems to be breaking.

I was wondering if some patch or minor is causing the entire 2.3.x to break

**Comment by jesus-seijas-sp** [comment]
The problem seems to be a breaking change on a minor version of one dependency, related with the fast-glob dependency. Upgrading to 2.5.0 fix the problem.

But I highly recommend to upgrade to last version, always, given the fact that is the one faster, with better accuracy, and better identification of false positives.

**Comment by Nahdus** [comment]
Thanks, that helped. ;)
