### ISSUE TITLE
Disable builtin entity matching at will

### ISSUE THREAD

**Issue by qwertyuu** [axa-group/nlp.js#253]
First of all, thanks a lot for the amazing library. Very nice to use and does what it needs to do. Bravo!

I've been experimenting the past few days with the engine and sometimes the `nlp-manager.process` calls were taking quite a bit long, like 3-4 seconds per call. I thought it was weird so I used V8 profiling to see the root of the problem. What I found is that microsoft's `recognizers-text-suite` uses many XRegExp calls and is very slow when searching for entities.

**Is your feature request related to a problem? Please describe.**
Since I do not plan on using builtin entities, I would like to have a way to disable them. I found a way to do it manually by going into `lib/ner/ner-manager.js` and setting `includeBuiltin` to false. This skipped the builtin entity search and `nlp-manager.process` effectively dropped to less than one second per query.

**Describe the solution you'd like**
I would like to be able to at least disable builtin entity matching, or at least make it fast enough to be worth keeping around.

**Describe alternatives you've considered**
I suspect that the recognizers might be called too often than necessary, but I have not dug that way, making them "responsible" for long wait times, but they might just be called way too many times when processing the utterance.

**Comment by jesus-seijas-sp** [comment]
Hello! You can achieve that providing settings to the constructor of the NlpManager, like this:

```javascript
  const manager = new NlpManager({ ner: { builtins: [] } });
```

There you're telling the NlpManager that the NER part should process the builtins types in the list, as the list is empty it will not process any builtin.

The list of builtins that you can provide:
```javascript
    this.builtins = this.settings.builtins || [
      'Number',
      'Ordinal',
      'Percentage',
      'Age',
      'Currency',
      'Dimension',
      'Temperature',
      'DateTime',
      'PhoneNumber',
      'IpAddress',
      'Boolean',
      'Email',
      'Hashtag',
      'URL',
    ];
```

**Comment by jesus-seijas-sp** [comment]
@qwertyuu On the other hand... I will push the code that I'm currently working on that is for using Duckling as an alternative to the Microsoft Recognizers-Text. But that means that you'll need to have a Duckling instance deployed.

**Comment by qwertyuu** [comment]
Thanks a whole lot for the quick reply! 😸 

Also, I fiddled a little and found that a list of builtins was saved with my model after training, and would overwrite my NerManager'S builtins. Since it does not seem possible to setup builtins from nlp.js-app training, I needed to manually set the builtins to [] just after loading from the file.
Ex.:
```js
nlpManager.load('./model.nlp'); // Contains a list of builtins included in nlp.js-app training
nlpManager.nerManager.builtins = [];
```

**Comment by qwertyuu** [comment]
@jesus-seijas-sp Since the new 3.9.0 version, there were a change in my example that made it not work as expected.
The internals of the nerManager has changed to make ways to duckling, therefore this is what I needed to do:
```js
nlpManager.load('./model.nlp');
nlpManager.nerManager.nerRecognizer.builtins = [];
```

**Comment by jesus-seijas-sp** [comment]
Yes, sorry, it was an API change, that's the reason of the major... Right now the nerManager can use the nerRecognizer (recognizers-text) or the ducling one (through API)

**Comment by qwertyuu** [comment]
Yes thank you, I will surely try duckling out soon!
