### ISSUE TITLE
Separate messages for a response

### ISSUE THREAD

**Issue by adantoscano** [axa-group/nlp.js#257]
**Is your feature request related to a problem? Please describe.**
I would like to get a more complex generated response. i.e: Separate messages to answer a question.

**Describe the solution you'd like**
Get any property in response that returns an array

**Describe alternatives you've considered**
I tried adding an array as response and there is no problem but `procces()` throws an error. I think, trying to render handelbars template. So if the response is an array, map it to render all and create a new response prop, like `fullAnswer`, to do not break `answer` use.

**Comment by jesus-seijas-sp** [comment]
Hello!

PR merged: https://github.com/axa-group/nlp.js/pull/258

It traverse in deep any kind of object or array, so you can provide also an object as answer.

Example of use:

```javascript
const { NlpManager } = require('node-nlp');

(async () => {
  const manager = new NlpManager({ languages: ['en'] });
  manager.addDocument('en', 'goodbye for now', 'greetings.bye');
  manager.addDocument('en', 'i must go', 'greetings.bye');
  manager.addDocument('en', 'hello', 'greetings.hello');
  manager.addDocument('en', 'hi', 'greetings.hello');
  manager.addAnswer('en', 'greetings.bye', ['bye {{name}}']);
  const answer = [
    {
      name: '{{ name }}',
      beer: '{{ beer }}'
    },
    'My name is {{ name }} and I want {{ amount }} {{ beer }}...',
    'thinking better put me {{ double(amount) }}']
  manager.addAnswer('en', 'greetings.hello', answer);
  await manager.train();
  const context = {
    name: 'Roberto',
    beer: 'Cruzcampo',
    amount: 1,
    double: x => 2 * x,
  }
  const result = await manager.process('en', 'hello', context);
  console.log(result);
})();
```

**Comment by adantoscano** [comment]
Wow! That was pretty fast. Thanks @jesus-seijas-sp
