### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by obaid** [axa-group/nlp.js#259]
**Describe the bug**
I noticed that 3.9.0 was released. Is there a way to know what changes went into it?

**To Reproduce**
N/A.

**Expected behavior**
A changelog or release notes section?

**Screenshots**
N/A.

**Desktop (please complete the following information):**
N/A.

**Additional context**
Currently I am reading through PRs to see what was merged.

**Comment by jesus-seijas-sp** [comment]
Now a changelog exists. Closing the issue.
