### ISSUE TITLE
Create browser dist with terser

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#269]
At package.json a task for generate the browser package is done using uglify.
As uglify-es is no longer mantained, this task should be updated using terser. 
https://github.com/terser/terser

Also, the web dist should be generated.

**Comment by danielcaldas** [comment]
Hey @jesus-seijas-sp is this one up for grabs?

**Comment by jesus-seijas-sp** [comment]
@danielcaldas of course!
