### ISSUE TITLE
Unexpected None

### ISSUE THREAD

**Issue by adantoscano** [axa-group/nlp.js#274]
**Describe the bug**
I am getting 'None' intent but in classifications I can find some intents with more value than my threshold in classifications

**To Reproduce**
1. `const manager = new NlpManager({ languages: ['es'], defaultThreshold: 0.3, nlu: { useNoneFeature: false } });`
2. Run procces() after training

**Expected behavior**
Get some intent with higher value than threshold.
I think is about sort in classifications because I'm getting two first classification elements with value 0 so is triggering [this](https://github.com/axa-group/nlp.js/blob/23a8d1ba316ef2efdf219da90d93ee2c0cea7b29/lib/nlu/nlu-manager.js#L254). And the next three got values 0.48, 0.27 and 0.24

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Node
 - Version: 10.15

**Comment by jesus-seijas-sp** [comment]
Hello!

Can you put some example to reproduce it? So I can add this example to the unit tests, reproduce the error, and find the root cause.

**Comment by adantoscano** [comment]
I cannot right now because I'm working with a big training file with some sensible data, so I must filter this before. But this is the classification im getting
```
classifications:
  [ { label: 'smalltalk.badwords', value: 0 },
     { label: 'Default Welcome Intent', value: 0 },
     { label: 'faq.issue4',
       value: 0.4855951714509806 },
     { label: 'faq.issue5',
       value: 0.2736269540813284 },
     { label:
        'faq.issue3',
       value: 0.240777874467691 },
     { label:
        'faq.issue2',
       value: 0 },
     { label:
        'faq.issue1',
       value: 0 }, ...
```

**Comment by jesus-seijas-sp** [comment]
Mmm... only one question more... are you using domains or all the intents are in the master domin?

**Comment by adantoscano** [comment]
I'm not using domains

**Comment by jesus-seijas-sp** [comment]
Hello, 
I was not able to reproduced, so I've put a patch in the code, a sort after receive the classifications at the NLU manager. PR here: https://github.com/axa-group/nlp.js/pull/275

Can you check that solves your problem?

**Comment by adantoscano** [comment]
Yup, working. It was pretty weird because two intents was always on top, between 5th first places, but with value = 0. I'll try to reproduce the same scenario.
Thanks again!
