### ISSUE TITLE
Tokenizer words

### ISSUE THREAD

**Issue by ran-j** [axa-group/nlp.js#3]
**Is your feature request related to a problem? Please describe.**
Machine learn, I need to tokenizer and stem words

**Describe the solution you'd like**
Create a function to tokenizer and stem

**Describe alternatives you've considered**
NaN

**Additional context**
My project https://github.com/ran-j/ChatBotNodeJS/blob/master/routes/index.js#L40

**Comment by jesus-seijas-sp** [comment]
Hi! As the project is based on Natural, it already includes the tokenizers and stemmers from it.
https://github.com/axa-group/nlp.js/blob/master/lib/nlp/nlp-util.js
There you have an utility that based on the locale return a tokenizer for this locale.
You can also visit Natural tokenizers for more options:
https://github.com/NaturalNode/natural/tree/master/lib/natural/tokenizers

**Comment by ran-j** [comment]
Sorry, and thanks for reply
