### ISSUE TITLE
Errors  in intent recognition

### ISSUE THREAD

**Issue by giannisesteart** [axa-group/nlp.js#306]
const manager = new NlpManager({ languages: ['en'] });
// Adds the utterances and intents for the NLP
  

//rigoros Security infos

manager.addDocument('en', ' Nice  meet you ', 'ExactRedundant');
manager.addDocument('en', 'K-D-K', 'Redundant');

   (async() => {
    await manager.train();
     manager.save("model.nlp"); 
    const response = await manager.process('el', "The 38-year-old telly star, starring for the first time on the cover of American Vogue," +
    		"let the magazine\'s cameras go into her luxurious home, which she describes as a minimal monastery ," +
    		" explaining how her unique design is inspired by and Axel Vervoordt    AND The 38-year-old telly star, starring for the first time on the cover of American Vogue," +
    		"let the magazine\'s cameras go into her luxurious home, which she describes as a minimal monastery ," +
	        " explaining how her unique design is inspired by and Axel Vervoordt");

    		                                      
    	   console.log(response); 
    		
   
})(); 

/**_________________________________________________________________________________
The above code sample gives:
    { label: 'Redundant', value: 0.8877540683824059 },
     { label: 'ExactRedundant', value: 0.11224593161759411 } ],
  intent: 'Redundant',
  domain: 'default',
  score: 0.8877540683824059,
This is a error!  K-D-K is not part of the text!

**Comment by giannisesteart** [comment]
At the beginning my Version >npm view node-nlp version
3.10.1

My Code the same as your Code
*******************************************************************************************
const { NlpManager } = require('node-nlp');

async function main() {
  const manager = new NlpManager({ languages: ['en'], nlu: { useNoneFeature: false } });

  manager.addDocument('en', ' Nice meet you ', 'ExactRedundant');
  manager.addDocument('en', 'K-D-K', 'Redundant');
  
  await manager.train();
  const response = await manager.process('en', "The 38-year-old telly star, starring for the first time on the cover of American Vogue," +
  "let the magazine's cameras go into her luxurious home, which she describes as a minimal monastery ," +
  " explaining how her unique design is inspired by and Axel Vervoordt AND The 38-year-old telly star, starring for the first time on the cover of American Vogue," +
  "let the magazine's cameras go into her luxurious home, which she describes as a minimal monastery ," +
  " explaining how her unique design is inspired by and Axel Vervoordt");
  console.log(response);
}

main();
_____________________________________________________________________________
gives me the outout!
_****************************************************************************

{ locale: 'en',
  localeIso2: 'en',
  language: 'English',
  utterance:
   'The 38-year-old telly star, starring for the first time on the cover of American Vogue,let the magazine\'s cameras go into her luxurious home, which she describes as a minimal monastery , explaining how her unique design is inspired by and Axel Vervoordt AND The 38-year-old telly star, starring for the first time on the cover of American Vogue,let the magazine\'s cameras go into her luxurious home, which she describes as a minimal monastery , explaining how her unique design is inspired by and Axel Vervoordt',
  classification:
   [ { label: 'Redundant', value: 0.8881761568072879 },
     { label: 'ExactRedundant', value: 0.11182384319271207 } ],
  intent: 'Redundant',
  domain: 'default',
  score: 0.8881761568072879,
  entities:
   [ { start: 4,
       end: 14,
       len: 11,
       accuracy: 0.95,
       sourceText: '38-year-old',
       utteranceText: '38-year-old',
       entity: 'age',
       resolution: [Object] },
     { start: 4,
       end: 10,
       len: 7,
       accuracy: 0.95,
       sourceText: '38-year',
       utteranceText: '38-year',
       entity: 'duration',
       resolution: [Object] },
     { start: 45,
       end: 49,
       len: 5,
       accuracy: 0.95,
       sourceText: 'first',
       utteranceText: 'first',
       entity: 'ordinal',
       resolution: [Object] },
     { start: 232,
       end: 268,
       len: 37,
       accuracy: 0.95,
       sourceText: 'by and Axel Vervoordt AND The 38-year',
       utteranceText: 'by and Axel Vervoordt AND The 38-year',
       entity: 'duration',
       resolution: [Object] },
     { start: 262,
       end: 272,
       len: 11,
       accuracy: 0.95,
       sourceText: '38-year-old',
       utteranceText: '38-year-old',
       entity: 'age',
       resolution: [Object] },
     { start: 303,
       end: 307,
       len: 5,
       accuracy: 0.95,
       sourceText: 'first',
       utteranceText: 'first',
       entity: 'ordinal',
       resolution: [Object] } ],
  sentiment:
   { score: 6.312,
     comparative: 0.06936263736263737,
     vote: 'positive',
     numWords: 91,
     numHits: 16,
     type: 'senticon',
     language: 'en' } }

**Comment by jesus-seijas-sp** [comment]
Hello,

Tested in windows, ubuntu and mac, and no way to reproduce it.

In fact you can see it in runkit:

https://runkit.com/jesus-seijas-sp/5db2ea6fda1579001a02ea11

![image](https://user-images.githubusercontent.com/15154218/67571295-e5a99600-f733-11e9-8194-09ea6112e3c5.png)

Can you try to reproduce it and share it in runkit? Thank you

**Comment by giannisesteart** [comment]
Yes, the error is in the version 2.5.2. In the Version 3.10.1 is all ok! This error was systematic:
Another example at the same testfunction above for version 2.5.2:
 manager.addDocument('en', ' Nice meet you ', 'ExactRedundant');
 manager.addDocument('en', 'code', 'Redundant');

gives me:
 classification: [
    { label: 'ExactRedundant', value: 0.5 },
    { label: 'Redundant', value: 0.5 }
  ],
Thats  was obvius a error.

However, node-nlp is a beautiful modul and its pitty to have relative scores: The readability from scores is confusing:
**Example 1:**
  manager.addDocument('en', 'Skype', 'Adress');
  manager.addDocument('en', 'Postal', 'ExactRedundant');
      --
  const response = await manager.process('en', '  Postal Skype');
  ---
**gives me :**
classifications: [
    { label: 'ExactRedundant', value: 0.5003637136920965 },
    { label: 'Adress', value: 0.49963628630790347 }
  ],
  intent: 'ExactRedundant',
I cannot interpret the scores: I have found Skype or Postal exact in phrase(score 1).

**Another query example:**

const response = await manager.process('en', 'Dolor sit amet  Postal  ');

**gives me:**
 
classifications: [
    { label: 'ExactRedundant', value: 1 },
    { label: 'Adress', value: 0 }
  ],
  intent: 'ExactRedundant',
In this case i can interpret the score: i have found only the Postal with score 1 (=Exact in Phrase) and not the Skype  

Thank you!

**Comment by jesus-seijas-sp** [comment]
Closing as this error was reproduced in version 2.x, that is no longer supported.
