### ISSUE TITLE
intent 'None' classified even if useNoneFeature = false

### ISSUE THREAD

**Issue by unr3al011** [axa-group/nlp.js#312]
I use NLPManager and have a string that is a partial match of a whole string but it is not classified correctly.

Is there a way to force classification and disable none intent?

I tried to use useNoneFeature = false but it made no difference.

Is is possible to disable none intent and force a classification where it goes by similarity?

Classifications are also always either 1 or 0 but never something like 0.86 or something like that?

**Comment by jesus-seijas-sp** [comment]
Well, the classifications array gives you all the classifications, so you only have to skip the first element of the array if it's None.

Classifications are done in numbers between 0 and 1, of course. You'll get a 1 if it's pretty sure that this is the answer, the best way is that the utterance that you provide have an stem firgerprint equal to a training data. 

We use several corpus to test the results, at https://github.com/axa-group/nlp.js/tree/master/examples/benchmark you have the tests with 5 of them: 3 of them are from the SIGDIAL22 paper to ensure that we get the top classifications on all over other NLPs. Then you have a corpus with 50 intents 5 utterances per intent in english and spanish, to check that the accuracy is over 0.98 in bot.

We also check it with other corpus that are internal, also to check that the accuracy is correct.

So if you're having problems with the classifications, perhaps you can share your corpus so I can study why is failing in this case, and comparing with other NLP providers.

**Comment by jesus-seijas-sp** [comment]
Closing
