### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by danbulant** [axa-group/nlp.js#313]
**Describe the bug**
Couldn't train the czech model as the following error happened

**To Reproduce**
1. make a simple bot, with the language set to cs
2. try to generate model

**Expected behavior**
Generate model

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome - Is it even needed?
 - Version 3.8.0

**Comment by jesus-seijas-sp** [comment]
First at all, I'm sorry about the bug, it was my fault. 
Should be fixed now in version 3.10.2, I published it minutes ago.

**Comment by danbulant** [comment]
OK, after updating everything worked. Thanks!
