### ISSUE TITLE
Bayes Classifier

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#32]
**Is your feature request related to a problem? Please describe.**
Currently a logistic regression classifier is used. Logistic regression classifier provides a great way to classify, but requires CPU intensive process to train.
A Bayes Classifier, on the other hand, don't need a CPU intensive process to train, so can grow in a progressive way without consuming time.
Why a Bayes Classifier is useful? 
While a frontend is being developed, that will mean that users will be able to add intents and try the bot in the fly. If a Logistic Regression Classifier is used while the user teach the bot, too much time will be consumed because the user will train so often. One solution is to use a Bayes Classifier while teaching, and when deploying then train with a logistic regression classifier. 
Also evaluate: it's possible to combine a Logistic Regression Classifier with a Bayes Classifier to get a better accuracy? Example: I've 30 intents, trained with Logistic Regression Classifier; I add a new intent, so if I write an utterance, it pass through the Bayes Classifier, if is identified as an intent that has been retrained continue with bayes, if is identified as an intent already trained with LRC, then pass through LRC.

**Comment by JasonShin** [comment]
Hey, @jesus-seijas-sp is this issue still relevant? I might be able to try it out for fun =) but I would appreciate any guidance

**Comment by jesus-seijas-sp** [comment]
Hello and welcome! The console-bot example is a good starting point, because is already training lots of utterance/entities using the logistic regression classifier.
For classifiers is already an abstract class: https://github.com/axa-group/nlp.js/blob/master/lib/classifiers/classifier.js
Every classifier must inherit from this one.
The logistic regression classifier is here:
https://github.com/axa-group/nlp.js/blob/master/lib/classifiers/logistic-regression-classifier.js
For the maths, vector an matrix are already implemented, and there is a library for mathematical operations here: https://github.com/axa-group/nlp.js/blob/master/lib/math/mathops.js

The idea is to implement a BayessianClassifier from the Classifier class, put a parameter in NlpClassifier to choose the classifier, and in the NlpManager the settings to pass to the NlpClassifier, so when creating the NlpManager you decide with kind of classifier you want to use. And that's all, for save/load another issue will be created.

And well, tests are done using jest, and the project is plenty of describing tests.

**Comment by jesus-seijas-sp** [comment]
Closed by https://github.com/axa-group/nlp.js/pull/97
