### ISSUE TITLE
[Question] Taking an action when answering 

### ISSUE THREAD

**Issue by chrisvel** [axa-group/nlp.js#331]
Is it possible to take an action = call a function when answering a question ?

For example when asking "what time is it" call `getTimeNow()` to get the current time?

**Comment by jesus-seijas-sp** [comment]
You can register actions. An example:

```javascript
const { dock } = require('../../packages/core/src');

(async () => {
  const container = await dock.createContainer();
  const nlp = container.get('nlp');
  nlp.addDocument('en', 'what is the weather?', 'weather');
  nlp.addAnswer('en', 'weather', 'the weather is');
  nlp.addAction('weather', 'getWeather', '', (input) => { return `${input.answer} sunny`});
  await nlp.train();
  const connector = container.get('console');
  connector.say('Now you can say something');
})();
```

To explain it better: addAction accepts 4 parameters:
- The intent that will raise the action
- The name of the action
- The parameters that will be used to call the action
- The function of the action (only to be registered once, by name... if two functions call the same action you have to register it only once).

When the intent is raised it identifyes the name of the action to be triggered. Then retrieve the function from a map by the name of the action. Finally calls the function passing as parameters the input object and the parameters you provided for this intent. Then the function can return an string that will be identifyid as the answer or you can even modify the input object adding or modifying whatever you need (even the classifications).

**Comment by chrisvel** [comment]
Thanks for the detailed reply
