### ISSUE TITLE
[Question] Loading from corpus 

### ISSUE THREAD

**Issue by chrisvel** [axa-group/nlp.js#332]
Can I use the `corpus.json` file to train my model instead of calling the `addDocument` and `addAnswer` methods as in example 1 but use it for examples 3 and 4 ?

**Comment by jesus-seijas-sp** [comment]
Well... If I understand you question... you can follow this steps. 
First one: clear the main method of the pipeline, so the pipelines.md file should look like that:
```markdown
# Pipelines

## console.hear
eq input.message "quit"
jne sendMessage
console.exit
label sendMessage
nlp.process input.message
.say input.answer

## main
```

Now the application will not automatically train neither say in console that is ready to hear.

Second step: modify the index.js so you manually retrieve the plugins from the container and use them:
```javascript
const { dock } = require('../../packages/core/src');

(async () => {
  const container = await dock.createContainer();
  const nlp = container.get('nlp');
  nlp.addCorpus('./corpus.json');
  await nlp.loadOrTrain();
  const connector = container.get('console');
  connector.say('Now you can say something');
})();
```

**Comment by chrisvel** [comment]
Aha, I left the corpus in the `conf.json`. 

Again, thanks for the detailed replies.
