### ISSUE TITLE
auto-stem example not working

### ISSUE THREAD

**Issue by bormat** [axa-group/nlp.js#334]
In the example for auto-stem
* there is scoreCorpus that is not defined and is not a npm repos so we don't know where this function came from
* when I do new TokenStemmer(NlpUtil.getTokenizer("pl")); 
I get  TokenStemmer is not a constructor and when I look the class it is BaseStemmer so yes it is not a constructor.

```
 const { NlpManager, NlpUtil } = require('node-nlp');
 const TokenStemmer = NlpUtil.getStemmer('pl');
 const tk = NlpUtil.getTokenizer("pl"); // instance of BaseStemmer
 const stemmer = new TokenStemmer(NlpUtil.getTokenizer("pl"));
 scoreCorpus(corpus, managerTokenizer); // no idea where this function is defined when i do a research on the repos I don't find it

```

**Comment by jesus-seijas-sp** [comment]
Hello,
The scoreCorpus function exists in the benchmark example, used to benchmark corpus based on havind utterances to train and utterances to test: https://github.com/axa-group/nlp.js/blob/v3.x/examples/benchmark/index.js

TokenStemmer is a typo, should be TokenizeStemmer:
https://github.com/axa-group/nlp.js/blob/v3.x/lib/nlp/stemmers/tokenize-stemmer.js

TokenizeStemmer is the stemmer that does nothing: it simply returns the array of words provided by the tokenizer.

**Comment by jesus-seijas-sp** [comment]
Closing. Auto-stemmer is no longer part of the project, now BERT tokenizer can be used.
