### ISSUE TITLE
Performance of findEntities. Any tips to improve?

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [axa-group/nlp.js#337]
I am using the the NerManager to create named entities and am also using the React Native version of the library.

For my use case there are 10,000 airports...this is the named entity I am adding...

```
        this.ner.addNamedEntityText(
            'airport',
            airport.airportId,
            ['en'],
            [airport.name, airport.shortName, getAirportAcronymn(airportCode," "), airportCode, getNatoPhonetic(airportCode)]
          );
```

I then am passing this content to findEntities...

What is the elevation of Allegheny County Airport

It takes 40+ seconds to return the result. It does successfully return  that there is an airport entity in the string.

When I get rid of all of the synonyms it still takes 15 seconds. Without the synonyms though, it wouldn't be that useful because there are multiple ways to say.

For this use case I am only adding one named entity type, but I assume if I add many more the performance would keep decreasing.

Any tips?

**Comment by claytongulick** [comment]
I'm running into similar issues with medical terms

**Comment by jesus-seijas-sp** [comment]
Hello!
I'm on it, but it will work fast only if the threshold is 1, that means, when you will find an exact match (right now the NER allows the clients to mistake some characters, example, you can have an entity with the text "barcelona" and the user puts "barselona" and will be recognized using a fast levenshtein).

Basically I'm making right now for improve the performance when you're looking for an exacta match is to build a hashmap of all the options, splitting the sentences into words, and searching into the hashmap. As the time complexity of a hashmap is O(1) it's supposed to be pretty fast compared with levenshtein that is O(n*m).

For the developing I'm using a list of more than 20k airports, I expect to do the PR in the next days.

**Comment by jeffbonasso-ambifi** [comment]
Awesome. Thanks for the help and responsiveness! In my use case the input will be coming from a voice recognition engine so it should be an exact match.

**Comment by jesus-seijas-sp** [comment]
Hi, with my current code it runs very quick, 5 miliseconds to process totally an utterance (NLU, NLG, NER...) with more than 20k airports:

![image](https://user-images.githubusercontent.com/15154218/70371002-a68f6880-18cd-11ea-8e9a-c654cbef8586.png)

But I found one little thing about airports that you can see at the image: there are several cities called Barcelona with airports, and that happens with lot of cities with same name but in different countries, or cities with several airports. 

Currently my decission has been to return all of them, so same start and end, same accuracy, but different option where option is the code of the airport. 

It's this correct or you expect a different behaviour like returning only one, an option, and perhaps a field with the array of all potential options?

**Comment by jeffbonasso-ambifi** [comment]
Amazing Jesús! Your decision returning an array of them is perfect. Thank you so much for your quick work on this. I truly appreciate it! If there is a published branch that has this current work I can point to to test let me know, otherwise happy to wait until you publish on npm.

**Comment by jesus-seijas-sp** [comment]
Hello @jeffbonasso-ambifi now you have the code in master.
At https://github.com/axa-group/nlp.js/tree/master/examples/06-huge-ner you have an example using airports with the format of version 4, the way to set NER threshold to 1 is here: https://github.com/axa-group/nlp.js/blob/master/examples/06-huge-ner/conf.json#L17

If you prefer the version 3 format, it will be something like this:

```javascript
const { NlpManager } = require('node-nlp');
const airports = require('./airports.json');

(async () => {
  const manager = new NlpManager({
    languages: ['en'],
    ner: { threshold: 1 },
  });
  const airportKeys = Object.keys(airports);
  for (let i = 0; i < airportKeys.length; i += 1) {
    const airport = airports[airportKeys[i]];
    manager.addNamedEntityText('airport', airport.icao, ['en'], airport.city);
  }
  let result = await manager.process('I want to go to Albacete');
  console.log(result.entities);
  result = await manager.process('I want to go to Barcelona');
  console.log(result.entities);
})();
```

**Comment by jeffbonasso-ambifi** [comment]
Thank you!!! I am using the React Native version. Do these changes now apply to that version now as well? Should I link to the react-native branch from master for that one?

**Comment by jeffbonasso-ambifi** [comment]
Hello Jesús. I was taking a look at your commit to see if it can be applied to the react-native branch, and it doesn't seem like a simple  mapping, unless I am missing something. Is the React Native version a completely different code base and will it be difficult to apply the changes you made in master to that branch as well?

**Comment by jesus-seijas-sp** [comment]
Hello @jeffbonasso-ambifi , the React Native branch is for the version 3.x... The version 3.x is monolithic, so to get the react native version what is done is to "rip off" the dependencies that does not work in react native (chinese language, japanese language, excel things...).

The version 4.x is splitted into small packages, so you install only what you need... so basically the react native branch will not be needed as you can use only packages valid for react native.

There is also a big reduction of size of the packages. To put an example, the version 3.x minimized for web was bigger than 2.8 MB. With the 4.x you can have a chatbot in english training and running in the web with only 126KB, so is a reduction of 20x times.

If you need it in the version 3.x react native branch I can cherry pick and publish.

**Comment by jeffbonasso-ambifi** [comment]
Great news that v4 will no longer require a separate build and the ability to cherry pick. Is there any documentation yet to point to that shows a small example of cherry picking and what the imports would look like? I can try to try myself, but if you know off the top of your head, do you feel the example you added 06-huge-ner will pretty much work as is?

**Comment by jesus-seijas-sp** [comment]
I'm on it ;) I'm preparing a big PR with some things and improvements, including an example on how to do the example 06 compiled and minimized to web, so it will be also compatible with React Native. Just wait 12 hours!

**Comment by jeffbonasso-ambifi** [comment]
Awesome thanks! Definiteyl will wait. BTW...when I tried to install directly from git I get this error. Doesn't look like your package.json has a version number in it. Maybe you have automated build process that adds that?


```
npm i --save git+https://github.com/axa-group/nlp.js.git

npm ERR! Can't install git+https://github.com/axa-group/nlp.js.git#c7ea4d6dbb2964c2a17bdebbe1e0277042fdfedc: Missing package version

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeffbonasso/.npm/_logs/2019-12-09T21_33_46_050Z-debug.log
```

**Comment by jesus-seijas-sp** [comment]
This happens because of being a monorepo with lerna: the parent package.json of the repo is the lerna one that it needs to operate. The real packages are inside the packages folder. And the packages are deployed in npmjs under the @nlpjs org, except the node-nlp one that is for retrocompatibility with version 3.x. https://www.npmjs.com/search?q=%40nlpjs

**Comment by jeffbonasso-ambifi** [comment]
That clears up the confusion. I have been referencing node-nlp from npm. Thanks!

**Comment by jesus-seijas-sp** [comment]
Hello! I published the version 4.0.0-rc.5. An example of usage for your need:

the package.json:
```json
{
  "name": "nlpweb",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nlpjs/core": "^4.0.0-rc.5",
    "@nlpjs/lang-en": "^4.0.0-rc.5",
    "@nlpjs/nlp": "^4.0.0-rc.5",
    "@nlpjs/request": "^4.0.0-rc.5"
  }
}
```

And the index.js:
```javascript
const { containerBootstrap } = require('@nlpjs/core');
const { Nlp } = require('@nlpjs/nlp');
const { LangEn } = require('@nlpjs/lang-en');
const { fs } = require('@nlpjs/request');

const conf = {
  settings: {
    nlp: {
      languages: ['en'],
      trainByDomain: false,
      threshold: 0.5,
      corpora: [
        'https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/corpus.json'
      ]
    },
    ner: {
      threshold: 1
    }
  }
}

async function main() {
  const airports = await fs.readFile('https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/airports.json');
  const container = await containerBootstrap(conf);
  container.use(Nlp);
  container.use(LangEn);
  const nlp = container.get('nlp');
  await nlp.loadOrTrain();
  const airportKeys = Object.keys(airports);
  for (let i = 0; i < airportKeys.length; i += 1) {
    const airport = airports[airportKeys[i]];
    nlp.addNerRuleOptionTexts('en', 'airport', airport.icao, airport.city);
  }
  let answer = await nlp.process('I want to flight from Albacete');
  console.log(answer.entities);
  console.time('algo');
  answer = await nlp.process('I want to flight from Madrid to Las Vegas');
  console.timeEnd('algo');
  console.log(answer.entities);
}

main();
```

**Comment by jeffbonasso-ambifi** [comment]
Hello Jesús. I am trying in React Native, but immediately get undefined Unable to resolve 'fs' from the container-bootstrap.js project when import @nlpjs/core. Any ideas?

**Comment by jesus-seijas-sp** [comment]
I created rn alternatives without fs, path and crypto.
Try again with this package.json and code:

```json
{
  "name": "nlpweb",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nlpjs/core-rn": "^4.0.0-rc.6",
    "@nlpjs/lang-en": "^4.0.0-rc.5",
    "@nlpjs/nlp": "^4.0.0-rc.5",
    "@nlpjs/request-rn": "^4.0.0-rc.6"
  }
}
```

```javascript
const { containerBootstrap } = require('@nlpjs/core-rn');
const { Nlp } = require('@nlpjs/nlp');
const { LangEn } = require('@nlpjs/lang-en');
const { fs } = require('@nlpjs/request-rn');

const conf = {
  settings: {
    nlp: {
      languages: ['en'],
      trainByDomain: false,
      threshold: 0.5,
      corpora: [
        'https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/corpus.json'
      ]
    },
    ner: {
      threshold: 1
    }
  }
}

async function main() {
  const airports = await fs.readFile('https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/airports.json');
  const container = await containerBootstrap(conf);
  container.use(Nlp);
  container.use(LangEn);
  const nlp = container.get('nlp');
  await nlp.loadOrTrain();
  const airportKeys = Object.keys(airports);
  for (let i = 0; i < airportKeys.length; i += 1) {
    const airport = airports[airportKeys[i]];
    nlp.addNerRuleOptionTexts('en', 'airport', airport.icao, airport.city);
  }
  let answer = await nlp.process('I want to flight from Albacete');
  console.log(answer.entities);
  console.time('algo');
  answer = await nlp.process('I want to flight from Madrid to Las Vegas');
  console.timeEnd('algo');
  console.log(answer.entities);
}

main();
```

**Comment by jeffbonasso-ambifi** [comment]
Thanks. Getting there. Still some dependency issues. First it was saying couldn't find module path which seems like dependency in containerBootstrap. I manually installed that. After that it complained about perf_hooks. When I manually installed that it didn't like it because couldn't find main module index.js which indeed does not exist.

**Comment by jesus-seijas-sp** [comment]
ok, try updating @nlpjs/core-rn to version 4.0.0-rc.7 in package.json and npm install...
Now path is not used and the timer is done with date substraction, that should work in web.

**Comment by jeffbonasso-ambifi** [comment]
Hmm...did clean install of everything on React Native. Get Unable to resolve module 'fs' from 'node_modules/@nlpjs/core/src/container-bootstrap.js': fs could not be found within the project.

**Comment by jeffbonasso-ambifi** [comment]
When just add first import seems ok, but then when add @nlpjs/nlp get error.

**Comment by jesus-seijas-sp** [comment]
Hello! I was working hard, the problem was that @nlpjs/nlp and others were using @nlpjs/core. Right now I removed the fs, path, crypto and others from @nlpjs/core... 
In fact, it also has another impact: the web bundle has decreased to 300KB.

Package.json and code:

```json
{
  "name": "nlpweb",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nlpjs/core": "^4.0.0-rc.10",
    "@nlpjs/lang-en": "^4.0.0-rc.10",
    "@nlpjs/nlp": "^4.0.0-rc.10",
    "@nlpjs/request-rn": "^4.0.0-rc.6"
  }
}
```

```javascript
const { containerBootstrap } = require('@nlpjs/core');
const { Nlp } = require('@nlpjs/nlp');
const { LangEn } = require('@nlpjs/lang-en');
const { fs } = require('@nlpjs/request-rn');

const conf = {
  settings: {
    nlp: {
      languages: ['en'],
      trainByDomain: false,
      threshold: 0.5,
      corpora: [
        'https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/corpus.json'
      ]
    },
    ner: {
      threshold: 1
    }
  }
}

async function main() {
  const airports = await fs.readFile('https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/airports.json');
  const container = await containerBootstrap(conf);
  container.register('fs', fs);
  container.use(Nlp);
  container.use(LangEn);
  const nlp = container.get('nlp');
  await nlp.loadOrTrain();
  const airportKeys = Object.keys(airports);
  for (let i = 0; i < airportKeys.length; i += 1) {
    const airport = airports[airportKeys[i]];
    nlp.addNerRuleOptionTexts('en', 'airport', airport.icao, airport.city);
  }
  let answer = await nlp.process('I want to flight from Albacete');
  console.log(answer.entities);
  console.time('algo');
  answer = await nlp.process('I want to flight from Madrid to Las Vegas');
  console.timeEnd('algo');
  console.log(answer.entities);
}

main();
```

**Comment by jeffbonasso-ambifi** [comment]
I definitely appreciate the effort and great that has been more optimized!

It gets past the fs issue. This is now an error getting...

![image](https://user-images.githubusercontent.com/38217156/70704967-15d7d480-1ca1-11ea-97c4-5d709823f20c.png)

**Comment by jeffbonasso-ambifi** [comment]
When I try to manually install then get...

![image](https://user-images.githubusercontent.com/38217156/70705113-66e7c880-1ca1-11ea-808f-d28787739829.png)

**Comment by jesus-seijas-sp** [comment]
Ok, is good news, is because of the timer on the neural network, is the last step :) Give me 5 minutes

**Comment by jesus-seijas-sp** [comment]
Done! Update     "@nlpjs/nlp": "^4.0.0-rc.11",

**Comment by jeffbonasso-ambifi** [comment]
Awesome, no import errors now. I am getting this when running sample code. Any ideas?

```
.
.
.
RCTLog.js:47 Running application TestNlpNew3 ({
    initialProps =     {
    };
    rootTag = 21;
})
infoLog.js:16 Running "TestNlpNew3" with {"rootTag":21,"initialProps":{}}
logger.js:36 Epoch 1 loss 1 time 1ms
logger.js:36 Epoch 2 loss 0.9821780234743666 time 0ms
logger.js:36 Epoch 3 loss 0.7709459186791443 time 0ms
logger.js:36 Epoch 4 loss 0.5642662618148991 time 0ms
logger.js:36 Epoch 5 loss 0.3949646310528284 time 0ms
logger.js:36 Epoch 6 loss 0.268341039966857 time 0ms
logger.js:36 Epoch 7 loss 0.17861713346016353 time 0ms
logger.js:36 Epoch 8 loss 0.11720412419060006 time 0ms
logger.js:36 Epoch 9 loss 0.0761335730998961 time 0ms
logger.js:36 Epoch 10 loss 0.049102693642329075 time 0ms
logger.js:36 Epoch 11 loss 0.0315097264139302 time 0ms
logger.js:36 Epoch 12 loss 0.020149059190004495 time 0ms
logger.js:36 Epoch 13 loss 0.012853389673209066 time 0ms
logger.js:36 Epoch 14 loss 0.008186282765784033 time 0ms
logger.js:36 Epoch 15 loss 0.005208623125670527 time 0ms
logger.js:36 Epoch 16 loss 0.0033122212112070212 time 0ms
logger.js:36 Epoch 17 loss 0.0021058068644154598 time 0ms
logger.js:36 Epoch 18 loss 0.0013388342239462798 time 0ms
logger.js:36 Epoch 19 loss 0.000851379312711873 time 0ms
logger.js:36 Epoch 20 loss 0.0005415814536036323 time 0ms
logger.js:36 Epoch 21 loss 0.0003446609187472879 time 0ms
logger.js:36 Epoch 22 loss 0.0002194527407689149 time 0ms
logger.js:36 Epoch 23 loss 0.0001398093157749196 time 0ms
logger.js:36 Epoch 24 loss 0.0000891237734156201 time 0ms
logger.js:36 Epoch 25 loss 0.00005684902786122153 time 0ms
logger.js:36 Epoch 26 loss 0.00003628582080370307 time 0ms
Utils.js:62 []length: 0__proto__: Array(0)
Utils.js:65 algo: 38.282958984375ms
Utils.js:66 []length: 0__proto__: Array(0)
YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
Error: Corpus not found "https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/corpus.json"
Error: Corpus not found "https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/corpus.json"
    at Nlp.addCorpus$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:99385:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29288:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29463:24)
    at Generator.prototype.<computed> [as next] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29331:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29288:19)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29364:22)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29374:15
    at tryCallOne (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3242:14)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3343:17
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30728:21
console.warn @ YellowBox.js:71
onUnhandled @ Promise.js:37
onUnhandled @ rejection-tracking.js:71
(anonymous) @ JSTimers.js:250
_callTimer @ JSTimers.js:146
callTimers @ JSTimers.js:399
__callFunction @ MessageQueue.js:436
(anonymous) @ MessageQueue.js:111
__guard @ MessageQueue.js:384
callFunctionReturnFlushedQueue @ MessageQueue.js:110
(anonymous) @ debuggerWorker.js:69
```

**Comment by jesus-seijas-sp** [comment]
Well, in the settings we have specified the corpora, with the link:

```javascript
const conf = {
  settings: {
    nlp: {
      languages: ['en'],
      trainByDomain: false,
      threshold: 0.5,
      corpora: [
        'https://raw.githubusercontent.com/axa-group/nlp.js/master/examples/06-huge-ner/corpus.json'
      ]
    },
    ner: {
      threshold: 1
    }
  }
}
```

So it will try to load this corpora. To load it, it gets the "fs" instance from the IoC container, by default this fs is a mocked one so it works in web and react (file system will not exists there). 

In the code you'll see that I added this: 
```javascript
  const container = await containerBootstrap(conf);
  container.register('fs', fs);
```

and fs is loaded this way:
```javascript
const { fs } = require('@nlpjs/request-rn');
```

This is creating a fs that works with axios and should work in web and react native...

If in your case it does not works, then remove the corpora from the settings, the NER will still works,  and for training the IA you can still use the old fashing methods:
```javascript
  nlp.addDocument(locale, utterance, intent)
```

**Comment by jesus-seijas-sp** [comment]
in the other hand, same problem for loading airports: is loading them from a web link.
You can import a json instead, downloading the json from the link.

**Comment by jeffbonasso-ambifi** [comment]
A question...if I am just doing NER do I need the corpus file? Seems like it is for chatbot intents. If I don't need it would corpora just be null in config?

**Comment by jesus-seijas-sp** [comment]
Nope. If you don't add a corpus, then you'll receive that the intent is None (of course, no intent trained...) but you'll receive the entities as usual.

**Comment by jeffbonasso-ambifi** [comment]
Success! Did a full round robin in React Native and adding 50,000 rules and coming back almost instantaneous. When deploying to Release mode there was one issue I had to debug that doesn't show up when deploying Debug mode on device.

An issue when trying to process the slotManager, which I am not yet using. Error saying undefined for slotManager.process. Maybe there is a function I am supposed to be using when initializing to say using slot manager?

To get around it I commented out the following code in src/nlp.js

```
    // if (this.slotManager.process(output, context)) {
    //   output.entities.forEach(entity => {
    //     context[entity.entity] = entity.option || entity.utteranceText;
    //   });
    // }
    // context.slotFill = output.slotFill;
```

Thank you so much for your help and responsiveness!

**Comment by jesus-seijas-sp** [comment]
Hello! 
Can we close this issue?

**Comment by jeffbonasso-ambifi** [comment]
Yes. Thanks for all your help!

**Comment by jesus-seijas-sp** [comment]
Solved
