### ISSUE TITLE
ConversationContext is not a constructor

### ISSUE THREAD

**Issue by yanchespenda** [axa-group/nlp.js#359]
**Describe the bug**
I trying to use ConversationContext from node-nlp but i getting a TypeError

My Code:
```javascript
const { NlpManager, ConversationContext } = require('node-nlp');
const nlpManager = new NlpManager({
    languages: ['id'],
    nlu: {
        log: true
    }
});
const context = new ConversationContext();
```

**Screenshots**
My Code:
![Screenshot (335)](https://user-images.githubusercontent.com/13547711/71650857-a313c380-2d4b-11ea-959f-3102839e932c.png)
TypeError:
![Screenshot (334)](https://user-images.githubusercontent.com/13547711/71650860-a909a480-2d4b-11ea-9430-d0efa444a32f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 64 bit
 - Node.js version 11.5.0
 - Node-nlp version ^4.0.0-rc.16

**Comment by NeuronButter** [comment]
Not only that, but in addition, it doesn't have NerManager for me. I'm full serious, half the stuff that should be in there isn't.
![image](https://user-images.githubusercontent.com/33238007/71779528-2282ea80-300b-11ea-92b6-6c62e50ad079.png)

**Comment by NeuronButter** [comment]
Found a temporary fix, use `npm r node-nlp` to uninstall whichever version you have, then `npm i node-nlp@3.10.2` to download an older version. Leaving your code the same, it __should__ work. (Worked for me)

**Comment by yanchespenda** [comment]
Now i got a new TypeError: BaseNLU.classes[obj.className] is not a constructor

![Screenshot (340)](https://user-images.githubusercontent.com/13547711/71780923-1f7ffe00-2ffb-11ea-8ff9-09b29ab05993.png)

**Comment by jesus-seijas-sp** [comment]
Hello,

Yes, use the version 3 as the 4 is still a release candidate. 
About the new error: the file format of the version 4 is different, so what is happening to you is that you are reading a version 4 file from the version 3.

**Comment by rahulkathet** [comment]
Any solution this issue?

```
const context = new ConversationContext();
		                ^
TypeError: ConversationContext is not a constructor

```

**Comment by alexrqs** [comment]
Any documentation for Context on v4?
