### ISSUE TITLE
Where do I find the browser version?

### ISSUE THREAD

**Issue by S3bastiankoch** [axa-group/nlp.js#366]
I'm simply not able to find the browser version. Pls help :/

**Comment by jesus-seijas-sp** [comment]
Hello,
If you're talking about version 3.x, you have the broser version here: https://github.com/axa-group/nlp.js/tree/v3.x/dist

If you want to make browser/react native chatbots with version 4, I started a guide that you can find here: https://github.com/axa-group/nlp.js/blob/master/docs/v4/webandreact.md
I also suggest to read the quick start before: https://github.com/axa-group/nlp.js/blob/master/docs/v4/quickstart.md

**Comment by jesus-seijas-sp** [comment]
Closing as it was solved
