### ISSUE TITLE
nlpManager.loadExcel is not a function

### ISSUE THREAD

**Issue by etiennellipse** [axa-group/nlp.js#369]
Using v4.0.0-rc19, the method `loadExcel` does not exist on class `NlpManager`. We use this format to share training corpus with non technical staff and ease collaboration.

```
const nlp = require('node-nlp');

function trainExcel(excelFile, outputModel) {
    const nlpManager = new nlp.NlpManager();
    nlpManager.loadExcel(excelFile);
    nlpManager.train();
    nlpManager.save(outputModel, true);
}

trainExcel("TrainingData.xlsx", "model.nlp");

> node train.js
> ...
> TypeError: nlpManager.loadExcel is not a function
```

**Expected behavior**
I would expect the method to still, to ease the transition to v4.

**Desktop (please complete the following information):**
 - OS: MacOS
- Node.js v12
 - Version 4.0.0-rc19

**Comment by jesus-seijas-sp** [comment]
Fixed in version 4.0.2
