### ISSUE TITLE
Mathops exception when training on certain data

### ISSUE THREAD

**Issue by shadone** [axa-group/nlp.js#38]
**Describe the bug**
There is an exception being thrown from `lib/math/mathops.js:113` (`Unable to find minimum`) when training on certain data sets.

**To Reproduce**
```js
const { NlpManager } = require('./lib');

const manager = new NlpManager({ languages: ['nb'] });

manager.addDocument('nb', 'foo', 'foo');
const input = "Orkanen Florence treffer fredag østkysten av USA som en såkalt kategori 1-orkan."
manager.addDocument('nb', input, 'bar');

manager.train();
```

It seems to be triggered by the digits in the input - e.g. removing the digit `1` fixes it.

**Comment by post2seth** [comment]
Hello group,

I am seth from india, i am quite new for this repo, but i must say its a
great project and i love to contribute into this project if i can.

I need to know one thing ( which is quite lame) but i didnt get how i can
do this.

If i train a bot with data, how can i save that data will this
automatically save that and reaload on next load or i need to do that
manually? Please help me in this.

Regards
Seth Gaurav

**Comment by jesus-seijas-sp** [comment]
@shadone I will investigate that bug, I thing that can be related with the tokenizer and stemmer.

@post2seth NlpManager has methods to load/save to file. I will create an issue to document this, but you can take a look to the example at this lines:
https://github.com/axa-group/nlp.js/blob/master/examples/console-bot/train-nlp.js#L27
https://github.com/axa-group/nlp.js/blob/master/examples/console-bot/train-nlp.js#L502

**Comment by post2seth** [comment]
Thank you very much Jesus.

**Comment by jesus-seijas-sp** [comment]
Solved with https://github.com/axa-group/nlp.js/commit/cd1bafea32a4d546d414060d30c50a68c36f8ffe
Published version 1.3.1 with the patch. 

Also, take into account that the locale we use for norwegian is **no** instead of **nb**, and is very important because the stemmer is chosen based in the locale, so is expected that you get better results.

When you confirm that is solved I will close! 

Thank you!

**Comment by shadone** [comment]
It solved it for me, thanks for the quick fix!

**Comment by shadone** [comment]
It solved it for me, thanks for the quick fix!
