### ISSUE TITLE
Possible feature request

### ISSUE THREAD

**Issue by davidwallis3101** [axa-group/nlp.js#381]
I'm trying to create a bot for home and have configured some utterances and intents but I would like to do similar to those that use wordnet where I could define a verb such as "turn" using things like wordnet you could then say turn the light on, switch the light on, change then light for example (Crude example). You could then use the matched word to make the correct reply too.. I've turned, switched, changed the light

I'm very new to this libray (consumed via another project that uses this) and just wondering if thats something that can be done already or something that can be integrated with other libraries?

Thanks

**Comment by jesus-seijas-sp** [comment]
Hello, I'm not sure I understand completely your question... 
Wordnet is an online lexicon, so given a word you obtain the lemma, examples, etc... but is does not provides an AI to match sentences with intents.
With IoT usually I prefer to train as intents the actions, and the objects and rooms to interact with as entities. But as the scope of items is very limited it will work as well if you define all the intents.
But what I really recommend is to use Gladys. Gladys use nlp.js as the conversational AI, you can find the source code here: https://github.com/GladysAssistant/Gladys

**Comment by davidwallis3101** [comment]
thanks, I don't want to use another product - I was wondering if it was possible to use the definition of the word from wordnet I've seen some NLP engines that do this.. I was trying to avoid having to build every single intent or variation that could be used - Ill keep playing and see how I get on. Thanks.
