### ISSUE TITLE
addSlot not working in v4?

### ISSUE THREAD

**Issue by obaid** [axa-group/nlp.js#408]
**Describe the bug**
When running this: 
`manager.slotManager.addSlot(....);` 

in v4 it is not able to find `slotManager`

**To Reproduce**
Simply create a project using latest v4 and try to add a slot

**Expected behavior**
Should be able to add a slot.

**Screenshots**
N/A

**Desktop (please complete the following information):**
v4

**Additional context**

**Comment by nami20** [comment]
use manager.nlp.slotManager.addSlot(.....);

**Comment by aigloss** [comment]
Duplicate of https://github.com/axa-group/nlp.js/issues/410
