### ISSUE TITLE
Sentiment analyzer for Spanish

### ISSUE THREAD

**Issue by ftenrique** [axa-group/nlp.js#409]
**Describe the bug**
The sentiment analysis feature for the spanish language is broken.  I think I know the reason why.

**To Reproduce**
Test the SentimentAnalizer with a common word:  "rabioso" --> score = 0
Test it again with the stem of the word:  "rabios"  ---> score = -0.292
I checked the code and it is using the tokens directly, instead of the stems, resulting in very few hits.
Also checked the sentiment dictionary "senticon_es.json" and it uses stems, as it should, not full words to store the sentiment.

**Expected behavior**
Being able to get sentiment values for most phrases, not just a few.

Thank you Jesús for your awesome work in this library.

**Comment by ftenrique** [comment]
I have tried this on version 3.x and it works, this seems to be a regression in 4.x
Nobody else is using sentiment?

**Comment by jesus-seijas-sp** [comment]
Hello! It should be fixed in 4.3.0
