### ISSUE TITLE
Fatal error if no classifications match at all

### ISSUE THREAD

**Issue by qwertyuu** [axa-group/nlp.js#416]
Hello Jesus! We still love using the library and like that it is being developped so intensely. You are doing a wonderful job and we like to give feedback because it is always well received.

**Describe the bug**
After a long debugging session in the pipelines, I found that if the function `innerProcess` outputs an object with all classifications with a value of `0`, and then `convertToArray` is called, the output array is empty, which breaks further down the line:
```
Cannot read property 'intent' of undefined
DomainManager.innerClassify ([...]/node_modules/@nlpjs/nlu/src/domain-manager.js:313:48)
```

**To Reproduce**
Sadly, I cannot find a way to reproduce this issue at the moment without giving away too much concealed information publicly. I will try to make a specific reproduction process if it is really needed

**Expected behavior**
I expect either `convertToArray` to check that there is at least one classification and put the "None": 1 as a value if not, or to add a step in the pipeline that does just that, so that all other steps can then assume that the input array of classifications has always a value that is not an empty array when talking about classifications

**Desktop (please complete the following information):**
 - OS: Mac OS
 - NodeJS 12
 - Version 4.1.0

**Comment by jesus-seijas-sp** [comment]
It should be fixed now in 4.3.0
