### ISSUE TITLE
French alternative characters not normalized

### ISSUE THREAD

**Issue by qwertyuu** [axa-group/nlp.js#420]
Hello Jesus! I know the situation is bad with the COVID-19 and here we are forced to work from home, many have lost their jobs so I will open this issue with lots of compassion with the situation where you live, we are all very compassionate.
Thanks for the library and for all the work you do everyday.

**Describe the bug**
When testing our model, we found that sometimes, some sentences are not well classified. We found out that sometimes, our apostrophe are not the same depending on the OSes we use, or the keyboard layout we use.

By default, our "apostrophe" character is the same as the classic ASCII one, 
`'`
![image](https://user-images.githubusercontent.com/3145639/77476504-154af000-6df1-11ea-84dc-1dd83f933094.png)

But... SOMETIMES, this one gets printed out in our softwares (as I said, depending on the OS, keyboard layout, or software)
`’`
![image](https://user-images.githubusercontent.com/3145639/77476481-0e23e200-6df1-11ea-92ac-fc470b382cc0.png)

Which tricks the tokenizer in NLP.js into thinking it is not an apostrophe, and you get the idea. The character gets added to the output of the model when learning and is also not normalized when processing inputs. 
Things like: `“%school_subject%,en,eu,j’ai,mauvais,not,une”` are happening (look at the "j’ai" right in the middle)

**To Reproduce**
1. Train a model with an utterance that has "j’ai" in it, in French

**Expected behavior**
`“%school_subject%,en,eu,j’ai,mauvais,not,une”` should be `“%school_subject%,ai,en,eu,j,mauvais,not,une”`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Multiple, apple, iOS, web
 - Browser Chrome, Safari, etc.
 - Version 4.1.0

**Additional context**
Other utterances are properly tokenized with the original apostrophe `'` so I think normalizing or replacing this `’` somewhere in the pipeline should work.

**Comment by jesus-seijas-sp** [comment]
Hello, I changed the tokenizer of french so it split by characters instead of W+. 
Published as 4.3.0

**Comment by qwertyuu** [comment]
@jesus-seijas-sp Thanks, take care!
