### ISSUE TITLE
problem lang-es in bundle.js

### ISSUE THREAD

**Issue by santoscasta** [axa-group/nlp.js#428]
Try the example https://github.com/jesus-seijas-sp/nlpjs-examples/tree/master/02.web/01.bundle in spanish npm run browserdist failed to add this language.

**To Reproduce**
1. install @nlpjs/lang-es
2. Change in index.js "const langenmin = require('@nlpjs/lang-en-min') to const langenmin = require('@nlpjs/lang-es')
3. Load index.html

**Comment by aigloss** [comment]
Tested with following changes:

#### package.json:
```json 
  "dependencies": {
    "@nlpjs/core": "^4.23.4",
    "@nlpjs/lang-es": "^4.23.4",
    "@nlpjs/nlp": "^4.23.5"
  }
```
#### index.js
```js
const { containerBootstrap } = require("@nlpjs/core");
const { Nlp } = require("@nlpjs/nlp");
const { LangEs } = require("@nlpjs/lang-es");

(async () => {
  const container = await containerBootstrap();
  container.use(Nlp);
  container.use(LangEs);
```

resulting in no errors
