### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by calebeaires** [axa-group/nlp.js#43]
Is browser support on the roadmap? I have tried to use this module an Angular 6 application?

**Comment by jesus-seijas-sp** [comment]
Hello! 
The answer is yes, is one of the ideas for the 3.0. In fact, the debate about using lerna and split in a monorepo, is with the objective of having small pieces that can be imported independently, and this will allow to target browser without having a huge impact in the size (all the dictionaries for sentiment analysis, and so on).

**Comment by calebeaires** [comment]
Thats great. 

To some cases when dev with SPA apps made with with angular/react/vue, size is not such a problem!

**Comment by revolunet** [comment]
tried to compile with browserify or webpack but there is still an issue with `natural` + `memory-fs`.

the bundle size is around 3.5Mb

**Comment by jesus-seijas-sp** [comment]
Hi @revolunet and welcome! I'm working on having Natural out of the equation, implementing the tokenizers and stemmers. As soon as I finish, we can try again, and I expect that it will be possible to generate a frontend ready version.

**Comment by revolunet** [comment]
have you heard of https://github.com/Yomguithereal/talisman maybe ?

**Comment by jesus-seijas-sp** [comment]
Hi @revolunet, yes, but is not needed in this case, we have already the tokenizers/stemmers.
I've it working in the browser in the branch https://github.com/axa-group/nlp.js/tree/feature/without_natural
The bundle is 3.8MB.
The CON: No chinese due to tokenize using novel-segment, and novel-segment is not browser compatible at all. this branch is WIP, I will look for a way of doing novel-segment browser compatible, and also organize the code.
But right now... it's working!!!!
At the root you'll find bundle.js and an example index.html

**Comment by revolunet** [comment]
Hi,
Looks like the experimental branch is gone; is there a way to check it out to understand how far we are from browser support ?

**Comment by revolunet** [comment]
Ho 😻, that's pretty awesome, thanks a lot ! 
How did you build this file ?

**Comment by jesus-seijas-sp** [comment]
Well, I installed browserify and uglify-es globally: https://www.npmjs.com/package/uglify-es
then
```browserify ./lib | uglifyjs > ./dist/bundle.js```

**Comment by revolunet** [comment]
Would it be possible to "compute" the model on the server then just "consume" it on the client ?

**Comment by jseijas** [comment]
Yes of course

**Comment by linonetwo** [comment]
> The CON: No chinese due to tokenize using novel-segment, and novel-segment is not browser compatible at all. this branch is WIP, I will look for a way of doing novel-segment browser compatible, and also organize the code.

We are discussing how to make it browser compatible:
https://github.com/bluelovers/node-segment-dict/issues/1

**Comment by jesus-seijas-sp** [comment]
Closing as it was solved
