### ISSUE TITLE
How to work with context in v4.3.0

### ISSUE THREAD

**Issue by jnsntm** [axa-group/nlp.js#440]
**Description**
I am trying to use the context feature but i can't get it to work. I tried it exactly like in the doc.
Is is cause I'm trying it with the v3 doc (doc for v4 is not there yet?) and there have been some changes to the context behaviour in v4? 

**Steps to reproduce**
To reproduce simply grab the code from the docs and try it yourself. In my case the answer is 'Till next time, {{name}}!'

**Expected behaviour**
The expected behaviour would be 'Till next time, John!'

**Desktop:**
 - OS: macOS
 - Browser: Firefox
 - Package version: v4.3.0
 - Node version: v11.14.0

**Comment by Seixas** [comment]
same issue

**Comment by Apollon77** [comment]
documentation to be added in https://github.com/axa-group/nlp.js/pull/1171
