### ISSUE TITLE
Performance of NLP with process

### ISSUE THREAD

**Issue by dbatistat** [axa-group/nlp.js#443]
Hi!

After doing a search of libraries and NLP services, we stayed with NLP.js but we have noticed that the performance is not very good when we process a message. Is this normal? on my computer this delay is approximately 1000ms, It may not look like much (not for me) but in production each message takes from 8 seconds to 15 seconds and maybe is because we use GAE with 500mb of Ram, but we need to improve the performance of this.

**So my questions are:**
Any ideas to fix it or make it faster?
Will the time increase when we have more intents?

**My computer details:**
MacBook Pro 2,4 GHz Intel Core. Ram 32 GB 2400 MHz

**Test:**
nlpManager.process('es', 'cambiar pais')

**Test results:**
Test 1: 1064 ms
Test 2: 959 ms
Test 3: 1128 ms

**Intents**
It is a object for the training, `intent` is the key of the document.
```typescript
export const MESSAGE_INTENTS: MessageIntent[] = [
  {
    intent: Intent.PRODUCT,
    message: 'inicio'
  },
  {
    intent: Intent.PRODUCT,
    message: 'reiniciar'
  },
  {
    intent: Intent.PRODUCT,
    message: 'volver al inicio'
  },
  {
    intent: Intent.PRODUCT,
    message: 'quiero volver al inicio'
  },
  {
    intent: Intent.PRODUCT,
    message: 'menu'
  },
  {
    intent: Intent.PRODUCT,
    message: 'ir al menu'
  },
  {
    intent: Intent.PRODUCT,
    message: 'ver menu'
  },
  {
    intent: Intent.PRODUCT,
    message: 'ver el menu'
  },

  {
    intent: Intent.PRODUCT,
    message: 'cambiar producto'
  },
  {
    intent: Intent.PRODUCT,
    message: 'otro producto'
  },

  {
    intent: Intent.PRODUCT,
    message: 'cambiar servicio'
  },
  {
    intent: Intent.PRODUCT,
    message: 'otro servicio'
  },
  {
    intent: Intent.PRODUCT,
    message: 'comenzar de nuevo'
  },
  {
    intent: Intent.PRODUCT,
    message: 'iniciar otra vez'
  },
  {
    intent: Intent.PRODUCT,
    message: 'ver opciones'
  },
  {
    intent: Intent.PRODUCT,
    message: 'más opciones'
  },
  {
    intent: Intent.PRODUCT,
    message: 'mas opciones'
  },
  {
    intent: Intent.PRODUCT,
    message: 'otra opción'
  },
  {
    intent: Intent.PRODUCT,
    message: 'ver más opciones'
  },
  {
    intent: Intent.PRODUCT,
    message: 'comenzar de nuevo'
  },
  {
    intent: Intent.PRODUCT,
    message: 'iniciar de nuevo'
  },
  {
    intent: Intent.COUNTRY,
    message: 'pais'
  },
  {
    intent: Intent.COUNTRY,
    message: 'cambiar pais'
  },
  {
    intent: Intent.COUNTRY,
    message: 'quiero cambiar pais'
  },
  {
    intent: Intent.COUNTRY,
    message: 'otro pais'
  },
  {
    intent: Intent.COUNTRY,
    message: 'cambiar de pais'
  },
  {
    intent: Intent.COUNTRY,
    message: 'cambiar de país'
  },
  {
    intent: Intent.COUNTRY,
    message: 'otro país'
  },
  {
    intent: Intent.COUNTRY,
    message: 'otro pais'
  },
  {
    intent: Intent.RESET,
    message: 'reset'
  }
]
```

**Comment by jesus-seijas-sp** [comment]
Hello,
I uploaded a benchmark example here: https://github.com/axa-group/nlp.js/tree/master/examples/90-benchmark

As you can see it uses 2 corpus, one in english and another one in spanish. Each corpus haves 50 intents with 5 utterances per intent to train, and then is tested with 256 utterances, so a total of 512 tests are done. 

Those tests are done twice: one with builtins in the NER and one without builtins in the NER. This is the result:

![image](https://user-images.githubusercontent.com/15154218/81222243-43247680-8fe4-11ea-87e7-ad74d832b896.png)

Those times are measured in the worst environment that you can imagine... an old laptop, disconnected from AC Power so the performance is low, Windows 10...

With builtin entities I got 13 Transactions per second. 
Without builtin entities I got 1272 Transactions per second.

The difference: the builtin entities, by default, are processed by Microsoft Recognizers Suite, that is very slow. 
So you have two options: 
- If you don't need builtin entities, disable them as you can see in the code. The Enum, Trim and Regular Expression entities will work, enum are very optimized to work even with millions of conditions.
- If you need builtin entities, I suggest that you install duckling and integrate using this guide: https://github.com/axa-group/nlp.js/blob/master/docs/v3/builtin-duckling.md

**Comment by dbatistat** [comment]
Thanks @jesus-seijas-sp without builtins the performance improved from 1 sec to 0.005 ms

**Comment by akosbalasko** [comment]
@dbatistat I'm struggling with performance issues as well, and I'm glad to hear that disabling builtIns may solve the problem. May I ask which version do you use, and how did you disable to builtins for Ner?

Thank you very much!

**Comment by jesus-seijas-sp** [comment]
Hello @akosbalasko, in the example that I provided (example 90 in the folder examples) you have how to disable the builtins:

```javascript
const manager = new NlpManager({ ner: { builtins: [] }}); 
```

Disabling NER I get more than 2600 Transactions per second, when this thread was answered it was 1272, but since then several performance improvements were made, so I recommend you to use always the latest version. This is a comparision of Transactions Per Second with other platforms:

![image](https://user-images.githubusercontent.com/15154218/88101197-f2adc580-cb9d-11ea-87ef-3c2755ffdc69.png)

**Comment by akosbalasko** [comment]
Huh, I cannot decide who is faster, you or your code! :) Thank you @jesus-seijas-sp !

**Comment by jesus-seijas-sp** [comment]
After last improvements:

![image](https://user-images.githubusercontent.com/15154218/90110430-801fa800-dd4d-11ea-9307-7d19a74d4ffd.png)

So well... I think I can close this issue.
