### ISSUE TITLE
It is possible to have a new release?

### ISSUE THREAD

**Issue by luismsaraiva** [axa-group/nlp.js#449]
# Issue Template

Is it possible to create a new release?
I'm asking because I need the fix implemented in the Pull Request #432.

Cheers!!

## Your Environment

| Software             | Version |
|----------------------|---------|
| `nlp.js`             |   4.3.0   |
| `node`               |   10.12.0   |
| `npm`                |   6.4.1   |
| Operating System     |   Windows 10   |

**Comment by jesus-seijas-sp** [comment]
Hello, published as 4.4.0

**Comment by jesus-seijas-sp** [comment]
Closing, as the release was made.
