### ISSUE TITLE
Entity text overlap breaks intent classification with `nlpManager.process`

### ISSUE THREAD

**Issue by etiennellipse** [axa-group/nlp.js#460]
**Describe the bug**
Very similar as #388, reproduced with version 4.4.0!

When an entity text overlaps with another in the same entity definition, and the longer one is present in the input utterance, the intent classification result is skewed.  This only happens with entity text with multiple words.

**To Reproduce**
```
const nlp = require('node-nlp');

const locale = "fr";
const nlpManager = new nlp.NlpManager({ languages: [locale] });

nlpManager.addNamedEntityText(
    "problem",
    "understand",
    [locale],
    ["understanding", "my understanding"],
);

nlpManager.addDocument(locale, `I have a hard time with %problem%`, "hard_time_entity");

nlpManager.addDocument(locale, `I have a hard time with anything`, "hard_time_else");

nlpManager.train().then(() => {
    nlpManager.save('reproduce-model.nlp', false);

    nlpManager.process(locale, "I have a hard time with my understanding")
        .then((result) => console.log(result));
});
```

Result:
<img width="605" alt="Capture d’écran, le 2020-06-15 à 10 21 04" src="https://user-images.githubusercontent.com/13202064/84668807-0d7f8100-aef2-11ea-8b20-bbbae533a017.png">

**Expected behavior**
I would expect the returned classifications to be:
```
  classifications: [
    { intent: 'hard_time_entity', score: 1 }
  ],
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Package version 4.4.0
 - Node version v12.14.0

**Additional context**
The returned optionalUtterance is:
```
optionalUtterance: 'I have a hard time with %problem%%problem%'
```
which is breaking the intent detection down the road, I am pretty sure. This is the same thing as the problem we faced with #388.

**Comment by jesus-seijas-sp** [comment]
Hello, Take a look into the PR: https://github.com/axa-group/nlp.js/pull/461
Tomorrow I want to create a new version of NLP.js, so this PR should be included in the release.

**Comment by etiennellipse** [comment]
Fantastic, thanks for the quick action @jesus-seijas-sp
