### ISSUE TITLE
Documentation links on npmjs.com are broken

### ISSUE THREAD

**Issue by kras95** [axa-group/nlp.js#468]
**Describe the bug**
A lot of the links on npmjs.com are leading to a 404 page. The nlp.js logo is also missing there.

**To Reproduce**
1. Go to https://www.npmjs.com/package/node-nlp
2. Click on "NLP Manager" in the "TABLE OF CONTENTS"
4. See 404 error

**Expected behavior**
I think that for example, the NLP Manager link should lead here instead:
https://github.com/axa-group/nlp.js/blob/master/docs/v3/nlp-manager.md

**Screenshots**
![image](https://user-images.githubusercontent.com/52287634/84883599-62113080-b099-11ea-8a84-c4b7e65ac06f.png)

**Comment by vvscode** [comment]
currently it works for me https://github.com/axa-group/nlp.js/blob/HEAD/docs/v3/nlp-manager.md

**Comment by jesus-seijas-sp** [comment]
Hello, 
This is fixed with the last publish of the library.

**Comment by vvscode** [comment]
closing? ))

**Comment by jesus-seijas-sp** [comment]
Ooops! Yes, closing!
