### ISSUE TITLE
TypeError: NerManager is not a constructor

### ISSUE THREAD

**Issue by KGuzikowski** [axa-group/nlp.js#511]
Hi, I'm new to nlp.js and this may not be a bug. I followed docs for **NerManager** and I want to import and use it like this:
```
const { NerManager } = require('node-nlp');

const manager = new NerManager({
	threshold: 0.3,
	builtinWhitelist: [],
});
```
It's exactly like docs says. But I see this error in the console:

```
const manager = new NerManager({
                ^
TypeError: NerManager is not a constructor
```
I don't see NerManager export in 'node-nlp'. So how can I access it? There's nothing in docs.
I run it with node.

**Comment by nfreear** [comment]
Hi Karol / @KGuzikowski,

If you're using the latest code -- `master` branch / `4.x`, then the code-base is split into individual packages, of which one in `ner`,

 * https://github.com/axa-group/nlp.js/tree/master/packages/ner;

You may want to look at the [quickstart](https://github.com/axa-group/nlp.js/blob/master/docs/v4/quickstart.md), and @jesus-seijas-sp's advice is #395.

(FYI, the `3.x` branch is monolithic.)

I hope that gets you going!

Best wishes,

Nick (UK).

**Comment by KGuzikowski** [comment]
@nfreear thanks for answering me. It does help. But I have some more questions since docs for v4 are not full yet.

I have such code(I wrote it based on code in @nlpjs/ner:

`
const { Ner } = require('@nlpjs/ner');
const testingDataShort = require('./testingDataShort');

const manager = new Ner({
	languages: ['de'],
	threshold: 0.3,
});

(async () => {
	for (const x of testingDataShort) {
		const result = await manager.getEntitiesFromUtterance('de', x);
		console.log(result);
	}
})();
`
And all results are empty arrays. So it doesn't work. Like I said docs doesn't say much about entity extraction with v4. They explain it on NerManager which is not in v4 now.

Does have any idea whay my code would not work?

**Comment by KGuzikowski** [comment]
Hi, @nfreear thanks for answering. I see that NlpManager uses Ner under the hood. I see that NerManager has methods for adding rege entities and methods for extracting them. Docs doesn't say anything about this. I have this code for version 4: 

```
const { NlpManager } = require('node-nlp');
const testingDataShort = require('./testingDataShort');

const manager = new NlpManager({
	languages: ['de'],
	nlu: { useNoneFeature: true },
	ner: { builtins: [] },
});

manager.addRegexEntity(
	'de',
	'street_address',
	'/[a-z-]+s([0-9]{1,3})([a-zA-Z][0-9]?)?(([/-])([0-9]{1,3})([azA-Z][0-9]?)?)?/gi',
);
manager.addRegexEntity('de', 'zip_code', '/\d{5}/gi');
manager.addRegexEntity('de', 'city', '/[a-z]+/gi');

(async () => {
	console.log('Starting training');
	await manager.train();
	console.log('Training comleted');

	for (const x of testingDataShort) {
		const result = await manager.extractEntities(
			'de',
			x,
			{},
			{ threshold: 0.3 },
		);
		console.log(result);
	}
})();
```
I doesn't extract any entities I defined. Docs doesn't say anything about this so I wonder if this is correct.

**Comment by jesus-seijas-sp** [comment]
Hello @KGuzikowski : 
In V3 the signature for adding entities was (name, languages, ...).
In V4 the signature changed to (languages, name,...).

But node-nlp try to fit to V3... so in your case switching name with locale should be enough.

If you want to extract entities directly with the NER, this example will help you:
https://runkit.com/jesus-seijas-sp/5f1e8ed7d2a7f4001a8e9a8b

The idea in V4 with the NER is that you can build your own plugins for extraction, replace the existing ones or build your own pipelines to orchestrate extraction, that's why NER is not so simple as in V3 where the NER was "As Is".

**Comment by KGuzikowski** [comment]
Thank you a lot.

**Comment by mvillaizan** [comment]
> Hello @KGuzikowski :
> In V3 the signature for adding entities was (name, languages, ...).
> In V4 the signature changed to (languages, name,...).
> 
> But node-nlp try to fit to V3... so in your case switching name with locale should be enough.
> 
> If you want to extract entities directly with the NER, this example will help you:
> https://runkit.com/jesus-seijas-sp/5f1e8ed7d2a7f4001a8e9a8b
> 
> The idea in V4 with the NER is that you can build your own plugins for extraction, replace the existing ones or build your own pipelines to orchestrate extraction, that's why NER is not so simple as in V3 where the NER was "As Is".

In the example given, how would the threshold be configured?

**Comment by jesus-seijas-sp** [comment]
> > Hello @KGuzikowski :
> > In V3 the signature for adding entities was (name, languages, ...).
> > In V4 the signature changed to (languages, name,...).
> > But node-nlp try to fit to V3... so in your case switching name with locale should be enough.
> > If you want to extract entities directly with the NER, this example will help you:
> > https://runkit.com/jesus-seijas-sp/5f1e8ed7d2a7f4001a8e9a8b
> > The idea in V4 with the NER is that you can build your own plugins for extraction, replace the existing ones or build your own pipelines to orchestrate extraction, that's why NER is not so simple as in V3 where the NER was "As Is".
> 
> In the example given, how would the threshold be configured?

Replacing 
```javascript
const ner = new Ner({ container });
```
with 
```javascript
const ner = new Ner({ container, threshold: 1 });
```
Where you can replace 1 with your threshold.
You have other example here:
https://github.com/jesus-seijas-sp/nlp-course/blob/master/04-ner/01-enum.js

**Comment by mvillaizan** [comment]
Thank you!
