### ISSUE TITLE
How to reset a language?

### ISSUE THREAD

**Issue by kootenpv** [axa-group/nlp.js#513]
I am wondering how I can reset a language completely? 
I'd like to be able to start with a clean slate, but I am not sure how to do this.

**Comment by kootenpv** [comment]
Is there a specific object that should be recreated?

**Comment by jesus-seijas-sp** [comment]
Hi, update to the version 4.10.1, and you will have a method removeLanguage, example:

```javascript
manager.removeLanguage('en');
```

**Comment by kootenpv** [comment]
Thanks that helped!
