### ISSUE TITLE
Pipelined.md is not working properly.

### ISSUE THREAD

**Issue by sheikh-haziq** [axa-group/nlp.js#521]
**my pipeline.md**

   # default

## onIntent(joke.chucknorris)
// compiler=javascript
const something = request.get('http://api.icndb.com/jokes/random');
if (something && something.value && something.value.joke) {
  input.answer = something.value.joke;
}

(node:4880) UnhandledPromiseRejectionWarning: Error: Path not found in pipeline "request.get('http://api.icndb.com/jokes/random');"
    at Container.resolvePathWithType (E:\Haziq\Trial Apps\AI\chatbot\node_modules\@nlpjs\core\src\container.js:191:17)
    at DefaultCompiler.executeReference (E:\Haziq\Trial Apps\AI\chatbot\node_modules\@nlpjs\core\src\default-compiler.js:137:24)
    at DefaultCompiler.executeAction (E:\Haziq\Trial Apps\AI\chatbot\node_modules\@nlpjs\core\src\default-compiler.js:280:21)
    at DefaultCompiler.execute (E:\Haziq\Trial Apps\AI\chatbot\node_modules\@nlpjs\core\src\default-compiler.js:308:26)
(node:4880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:4880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jesus-seijas-sp** [comment]
I downloaded again the example of the guidelines, found here:
https://github.com/jesus-seijas-sp/nlpjs-examples/tree/master/01.quickstart/12.onintent
I did npm install and node ., went to localhost:3000, and it worked perfectly.

Then I updated all the dependencies, to see if it is a bug in new versions. After updating, it worked perfectly.

Then I tried something different: breaking the format of the markdown
The original:
```markdown
## onIntent(joke.chucknorris)
// compiler=javascript
const something = request.get('http://api.icndb.com/jokes/random');
...
```

I put some spaces in front of the comment // compiler:

```markdown
## onIntent(joke.chucknorris)
  // compiler=javascript
const something = request.get('http://api.icndb.com/jokes/random');
...
```
That way I reproduced your bug... 
So I suggest that you revise your markdown script, it seems to be bad formatted.
