### ISSUE TITLE
Proposed PR :~ add the "user ID" to the input for NLP.js plugins

### ISSUE THREAD

**Issue by nfreear** [axa-group/nlp.js#546]
Hi @jesus-seijas-sp and contributors,

I'd like to submit a pull request for this — I'm gauging interest!

Thank you!

**Is your feature request related to a problem? Please describe.**

 * Use-case 1 :~ in an _Internet of Things_ context I'd like to be able to switch on my light, not my neighbours!

 * Use case 2 :~ I'd like the option to "_Remember my location is Milton Keynes_", ... then later, for example, "_Get me the local weather_".

**Describe the solution you'd like**
My proposal appears to only need 1 line added to each of two Javascript files:

 1. Add `from: activity.from` to [`directline-controller.js` — `addActivity()` — line 161-162](https://github.com/axa-group/nlp.js/blob/master/packages/directline-connector/src/directline-controller.js#L161-L162);

 2. Add `context.from = sourceInput.from || null;` to [`nlp.js` — `process()` — line 474-475](https://github.com/axa-group/nlp.js/blob/master/packages/nlp/src/nlp.js#L474-L475);

**Describe alternatives you've considered**
If there is a concern about unintended data-leakage from the front to backend (security), the modification in `directline-controller.js` could be made optional, depending on a feature-flag, for example:

```js
            nlp
              .process({
                message: activity.text,
                // ...
                from: process.env.SHARE_USER_DATA_WITH_PLUGINS ? activity.from : null,
              })
              .then // ...
```

**Additional context**
The `from` object takes the form:

```js
{
  id: 'jo.bloggs@example.com',  // Numeric ID, UUID, username, or email address used as the ID.
  name: 'Jo Bloggs',  // Display name or empty string.
  role: 'user'
}
```

The `id` is set via [`WebChat.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/API.md#userID):

```js
WebChat.renderWebChat({
  // ...

  userID: 'jo.bloggs@example.com'

});
```

And, the input to a plugin's `run()` method becomes:

```js
{
  utterance: 'Remember my location is Milton Keynes',
  intent: 'store.location',
  // ...
  from: {
    id: // ...
  }
}
```

Does this sound OK?

Yours,

Nick

**Comment by nfreear** [comment]
Hi @jesus-seijas-sp and developers,

Would you like me to submit the pull request that I propose above please?

Thanks,

Nick

**Comment by jesus-seijas-sp** [comment]
Hello @nfreear 👍 Yes, a PR will be welcome.

**Comment by nfreear** [comment]
Fixed I think ...! N.
