### ISSUE TITLE
Update NLP classifier documentation

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#60]
**Describe the bug**
https://github.com/axa-group/nlp.js/blob/master/docs/nlp-classifier.md
Must be updated to have Tamil(ta) and 27 instead of 26 languages

**Comment by mauricetmeyer** [comment]
I would like to take on this as part of the Hacktoberfest.

**Comment by jesus-seijas-sp** [comment]
Thank you for your contribution!
