### ISSUE TITLE
Can I add custom data for sentiment analysis in version 4?

### ISSUE THREAD

**Issue by binsarjr** [axa-group/nlp.js#608]
Hi all.
I would like to add specific data for sentiment analysis using my country's language.

thank you

**Comment by jesus-seijas-sp** [comment]
Hello, 
I added sentiment analysis for almost all languages, published in versions 4.14.0

**Comment by binsarjr** [comment]
sentiment analysis nlp.js does not support Indonesian. perhaps due to a lack of data. so I want to add data from Indonesian. how do i do it?

**Comment by binsarjr** [comment]
This is the Indonesian language analysis sentiment data that I have collected

[Sentiment Analysis data from indonesian language](https://github.com/binsarjr/nodejs-chatbot-indonesia/tree/master/dataset/sentiment)

**Comment by jesus-seijas-sp** [comment]
hello,
In the documentation of Indonesian you have an example of sentiment analysis.
https://github.com/axa-group/nlp.js/tree/master/packages/lang-id

The afinn dictionary is located here: https://raw.githubusercontent.com/axa-group/nlp.js/master/packages/lang-id/src/sentiment/afinn_id.json

About how to modify the sentiment dictionary, here one example setting that the word "love" has value 10 at indonesian afinn dictionary:

```javascript
const { Container } = require('@nlpjs/core');
const { SentimentAnalyzer } = require('@nlpjs/sentiment');
const { LangId } = require('@nlpjs/lang-id');

(async () => {
  const container = new Container();
  container.use(LangId);
  const sentimentId = container.get('sentiment-id');
  sentimentId.afinn.love = 10;
  const sentiment = new SentimentAnalyzer({ container });
  const result = await sentiment.process({
    locale: 'id',
    text: 'kucing itu mengagumkan love',
  });
  console.log(result.sentiment);
})();
```

**Comment by binsarjr** [comment]
thanks. i will try it
