### ISSUE TITLE
Document context

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#63]
**Describe the bug**
Currently a context object can be provided to the NlpManger.process(). The NLG answers can be conditional based on conditions on context variables. This is described in the tests and the excel provided in the tests "It should use context if conversation id is provided":
https://github.com/axa-group/nlp.js/blob/master/test/recognizer/recognizer.test.js

Also, the Microsoft Recognizer, automatically creates a context manager, so when inside a conversation it adds the last retrieved entities into the conversation. 

This allows something like that: Suppose that you have two intents: 
- whois: Who is %hero%
- powers: Which are the powers of %hero%
And you have 2 heros: Hulk and Spiderman
- if hero is hulk then whois returns "Bruce Banner"
- if hero is Spiderman then whois returns "Peter Parker"
- if hero is hulk then powers returns "Super-Strengh"
- if hero is Spiderman then powers returns "Super-Agility"

This allows to get a conversation like:
user> Who is Spiderman?
bot> Peter parker
user> Which are his powers?
bot> Super-agility

As you can see the second question does not contains the name of the hero because is automatically stored in the context so the user can continue the conversation without having to repeat it in each question.

**Comment by mauricetmeyer** [comment]
@jesus-seijas-sp I would like to work on this issue. Is my understanding correct, that you would like to have this documented in the [nlp-manager.md](https://github.com/axa-group/nlp.js/blob/master/docs/nlp-manager.md) doc? Also is there a specific place in the file where it should be?

**Comment by jesus-seijas-sp** [comment]
@mauricetmeyer that's correct, must be documented as a new section at nlp-manager.md, the section must be also in the table of content at the README.md

**Comment by mauricetmeyer** [comment]
@jesus-seijas-sp One thing isn't really clear for me. What exactly should be documented, The Context Object itself, Providing a ConversationContext/Object to NlpManager.process directly or the use of the Recognizer class?

**Comment by jesus-seijas-sp** [comment]
@mauricetmeyer Currently the context feature exists. You can provide a context to the NlpManger.process so the NLG changes its behaviour based on the context. You have an example to train a bot with responses based on context here: https://github.com/axa-group/nlp.js/blob/master/test/nlp/rules.xls
But this feature is not documented anywhere.

Also the Recognizer class automatically creates and maintain the context, so for Microsoft Bot Framework chatbots this context is totally transparent to the developer. And is also not documented.

**Comment by mauricetmeyer** [comment]
@jesus-seijas-sp Thanks for clarifying. I hope it's ok to use your provided example for the docs.

**Comment by jesus-seijas-sp** [comment]
Thanks for your contribution!
Closed with https://github.com/axa-group/nlp.js/pull/71
