### ISSUE TITLE
Model.nlp is always created even when saving with a different name bug?

### ISSUE THREAD

**Issue by adelriosantiago** [axa-group/nlp.js#667]
**Describe the bug**
When `manager.save("abc.nlp")` a _model.nlp_ is also created.

![image](https://user-images.githubusercontent.com/5462382/95690527-2406c200-0bde-11eb-8e89-4187d13896f7.png)

Additionally _abc.nlp_ contains `"modelFileName": "model.nlp"` in its `settings` key.

![image](https://user-images.githubusercontent.com/5462382/95690540-37b22880-0bde-11eb-9b88-44e00fe3b9ad.png)

**Expected behavior**
I would expect only _abc.nlp_ to appear. Otherwise what is _model.nlp_?

**Desktop (please complete the following information):**
Windows, Node v12.18.3. node-nlp ^4.2.1.

**Comment by jesus-seijas-sp** [comment]
Hello,

I supose that you're using NlpManager. You can play with the _autoSave_ setting: if true, then it automatically save the model after train, with the name defined by _modelFileName_ setting. By default is true, and the modelFileName is "model.nlp".

This will disable autosave:
```javascript
const manager = new NlpManager({ autoSave: false, ... });
```

This will make that the model is automatically saved as "abc.nlp" so you don't have to call save method:
```javascript
const manager = new NlpManager({ modelFileName: 'abc.nlp', ... });
```

**Comment by adelriosantiago** [comment]
Ok great, thanks! I have expanded the docs to include that in https://github.com/axa-group/nlp.js/pull/673. Merge if you like it.
