### ISSUE TITLE
Remaining debug console.log

### ISSUE THREAD

**Issue by mathquis** [axa-group/nlp.js#703]
Hi!

It seems you left a debug console.log here:
https://github.com/axa-group/nlp.js/blob/1d8ff50b5cc3db4e8da9345b9f90027e25be7b9d/packages/nlu/src/domain-manager.js#L37

Cheers and thank you for this great library!

**Comment by jesus-seijas-sp** [comment]
Hello! Thank you for finding this! Already fixed

**Comment by mathquis** [comment]
Thanks!
Awesome lib by the way ;)
