### ISSUE TITLE
Web NLP loading corpus other than from web url?

### ISSUE THREAD

**Issue by MeetMartin** [axa-group/nlp.js#723]
I have followed the instructions from https://github.com/axa-group/nlp.js/blob/master/docs/v4/webandreact.md and it works to load a corpus from a URL like await nlp.addCorpus('https://raw.githubusercontent.com/jesus-seijas-sp/nlpjs-examples/master/01.quickstart/02.filecorpus/corpus-en.json');

but I don't seem to be able to load it locally await nlp.addCorpus('./corpus-en.json'); or by loading a model await nlp.load('./model.nlp');

Is there no other way to load a corpus than by providing a full web URL?

Thank you for your help.

**Comment by jesus-seijas-sp** [comment]
Hello, to the addCorpus method you can provide also an object containing the corpus. So you can obtain the corpus in any way you want, and provide the json.
