### ISSUE TITLE
Add prettier + husky hooks for formatting code on commit

### ISSUE THREAD

**Issue by vvscode** [axa-group/nlp.js#73]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but it would be much easier to maintain the project with prettier (less changes, single code style)

**Describe the solution you'd like**
Add prettier, and lint-staged/husky packages for formatting code on commit

**Comment by jesus-seijas-sp** [comment]
@vvscode That's a great idea! And thank you, I didn't used husky before, has a great look!

**Comment by vvscode** [comment]
I'll do. Probably it would be great changes by diff. However further it should be easier to support
