### ISSUE TITLE
Question : webchat 

### ISSUE THREAD

**Issue by torloneg** [axa-group/nlp.js#737]
hello
I wanted to create a new webchat or customize the existing one
where can I find the sources or examples ?

thanks

**Comment by jesus-seijas-sp** [comment]
Hello,
https://github.com/microsoft/BotFramework-WebChat/
The included webchat is the minimizable webchat example.

**Comment by ericzon** [comment]
Btw @torloneg once PR https://github.com/axa-group/nlp.js/pull/847 gets merged, you'll be able to point your customised public folder easily.

**Comment by ericzon** [comment]
This topic has been answered, otherwise, reopen it.
