### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by Enekaas** [axa-group/nlp.js#745]
when i use node-nlp, get this error:
**TypeError: manager.addAnswer(...) is not a function**

**Desktop:**
 - OS: ubuntu
 - Package 4.17.0
 - Node version 12

**Additional context**

**Comment by jesus-seijas-sp** [comment]
Can you please share your code? 
Meanwhile, here you have a runkit example of node-nlp:
https://runkit.com/jesus-seijas-sp/5fcdd8bb61fe6b0019d36738

**Comment by Enekaas** [comment]
when i want use the 'fa' language i get this error.
and i change this:
const manager = new NlpManager({ languages: ['fa'], forcfaER: true });
![1607534400590](https://user-images.githubusercontent.com/70912682/101663656-38d9c780-3a60-11eb-93b4-00409ddc3892.png)

**Comment by jesus-seijas-sp** [comment]
Hello,
You have typos. 
- First one in the NlpManager constructor you put "forcfaER" instead of "forceNER".
- Second one, in your picture, you are calling the method "addDocumfat" that does not exists and that's why is returning an error. The correct method is "addDocument"

**Comment by Enekaas** [comment]
Thank you very much, my problem was solved :)

**Comment by jesus-seijas-sp** [comment]
Closing as it is solved
