### ISSUE TITLE
Online course for free

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#757]
Hello al, I created a course con udemy about Conversatinal AI and NLP. The course includes how to use NLP.js but also how to use Brain.js and tensorflow. I have a promoción to get the course for free: https://www.udemy.com/course/conversational-ai/?couponCode=FREE4ALL

The link will work during three days.

**Comment by GuillermoPena** [comment]
I have take a look to the course but I can't see nothing about NlpManager (maybe I must check course deeply..)
I'm using NlpManager to classify texts with NERs, sentiment... etc Very very well. But, when a test fails I don't know how to see results of each step that NlpManager has done. Utterance after normalize, tokenize, remove stopWords, stemm... etc How can I do that? How can I access to normalizer, stemmer, tokenizer... that NlpManager is using?

**Comment by jesus-seijas-sp** [comment]
NlpManager is only there for compatibility with versión 3, that was monolithic. You asked about tokenizeAndStem and classifiers, and this is pretty well explained at the course using different technologies and benchmarking between them.
When I do chatbots I don't use NlpManager, it is not so flexible as using the plugins approach.
