### ISSUE TITLE
Detect gibberish

### ISSUE THREAD

**Issue by atulmy** [axa-group/nlp.js#768]
**Is your feature request related to a problem? Please describe.**
Sometimes when chatting with a chatbot application, users end up typing gibberish like: `asdasd sadasd` or `fgfsad dasdsa` etc. Is there a way to detect gibberish?

**Describe the solution you'd like**
Detect gibberish input using NLP

**Describe alternatives you've considered**
https://github.com/rrenaud/Gibberish-Detector (python based)

**Comment by jesus-seijas-sp** [comment]
Hello, 
I just published a new version that includes gibberish detection:

```javascript
const { isGibberish } = require('@nlpjs/utils');

console.log(isGibberish('This sentence is totally valid')); // false
console.log(isGibberish('Esta frase es totalmente correcta')); // false
console.log(isGibberish('ertrjiloifdfyyoiu')); // true
console.log(isGibberish('ajgñsgj ajdskfig jskf')); // true
```

You have also a function to give you the score, if you prefer the probability:

```javascript
const { gibberishScore } = require('@nlpjs/utils');

console.log(gibberishScore('This sentence is totally valid')); // 0
console.log(gibberishScore('Esta frase es totalmente correcta')); // 0.12
console.log(gibberishScore('ertrjiloifdfyyoiu')); // 0.57
console.log(gibberishScore('ajgñsgj ajdskfig jskf')); // 0.62
```

**Comment by atulmy** [comment]
Thanks, that was very quick!

I tested it out and found the result bit strange though, for example the probability for `very much` is `0.90`

```javascript
  console.log(gibberishScore('goodbye')); // 0.53
  console.log(gibberishScore('sure')); // 0.59
  console.log(gibberishScore('very much')); // 0.90
  console.log(gibberishScore('asddsa adsdsa asdadsasd')); // 0.52
```

Do we need to first process the text in anyway to get the gibberishScore right?

**Comment by jesus-seijas-sp** [comment]
Hello, I updated the algorithm. I was using 4 measures to detect gibberish:
- vowel frequency
- consonant frequency
- unique character frequency
- word over characters frequency
I replaced vowel frequency and consonant frequency with vowel over consonant ratio.
More changes done:
- y is considered a vowel
- Words with less than 6 characters are not considered gibberish
- The good range for words over characters is now (0.15, 0.3)
- The good range for unique characters is now (0.4, 1)
- The good range for vowel over consonant is (0.5, 1.5)

The unit tests:
```javascript
    test('Should return false for good sentences', () => {
      expect(isGibberish('This sentence is totally valid.')).toBeFalsy();
      expect(isGibberish('This is not gibberish')).toBeFalsy();
      expect(isGibberish('Esta frase es totalmente correcta')).toBeFalsy();
      expect(isGibberish('goodbye')).toBeFalsy();
      expect(isGibberish('sure')).toBeFalsy();
      expect(isGibberish('very much')).toBeFalsy();
    });
    test('Should return true for gibberish sentences', () => {
      expect(isGibberish('zxcvwerjasc')).toBeTruthy();
      expect(isGibberish('ertrjiloifdfyyoiu')).toBeTruthy();
      expect(isGibberish('ajgñsgj ajdskfig jskf')).toBeTruthy();
      expect(
        isGibberish('euzbfdhuifdgiuhdsiudvbdjibgdfijbfdsiuddsfhjibfsdifdhbfd')
      ).toBeTruthy();
      expect(isGibberish('nmnjcviburili,<>')).toBeTruthy();
      expect(isGibberish('ubkddhepwxfzmpc')).toBeTruthy();
      expect(isGibberish('kwinsghocyevlzep')).toBeTruthy();
      expect(isGibberish('ertrjiloifdfyyoiu')).toBeTruthy();
      expect(isGibberish('asddsa adsdsa asdadsasd')).toBeTruthy();
    });
```

**Comment by atulmy** [comment]
Thanks for super quick implementation! Works great 💪

**Comment by atulmy** [comment]
Strangely, I'm getting `NaN` for:
```javascript
console.log(gibberishScore('ioqwioeioqwe')) // NaN
```

**Comment by jesus-seijas-sp** [comment]
Hello @atulmy,
My fault, I didn't check the sign of an operation (1 - upper bound), so I was doing a Math.log over a negative number when checking for vowels over consonants ratio, because in this case the upper bound is 1.5. 
I also added a check to don't divide by 0.

Already published, and unit tests modified to include this new case.

**Comment by atulmy** [comment]
Thanks, works now :)

**Comment by atulmy** [comment]
```javascript
console.log(gibberishScore('it feels so good')) // 1
```

**Comment by jesus-seijas-sp** [comment]
There were an odd situation that produced a log(0), that is Infinity.
Fixed and published

**Comment by atulmy** [comment]
Thanks, works now :)

**Comment by atulmy** [comment]
```javascript
console.log(gibberishScore('are you a female?')) // 1
console.log(gibberishScore('are you a male?')) // -Infinity
```

**Comment by jesus-seijas-sp** [comment]
Hello, try updating to version 4.19.0, it should fix the problem

**Comment by atulmy** [comment]
Thanks, works now :)
