### ISSUE TITLE
Fix console-bot example to have async train

### ISSUE THREAD

**Issue by jesus-seijas-sp** [axa-group/nlp.js#77]
**Describe the bug**
Currently the example at https://github.com/axa-group/nlp.js/tree/master/examples/console-bot is not working properly, because the training now is asynchronous, so when the model is saved into file model.nlp, the weights are still not calculated.

**To Reproduce**
1. Run example console-bot so it will train and save into model.nlp
2. Exit the example and rerun so it will load model.nlp
3. Tell the bot "Who are you"
4. It will return "Sorry, I don't understand" because is not trained

**Recomended fix**

manager.train() must have an await, so the function must be async.
At index.js, wrap the main code in an async main() and run main().

**Comment by IamRaviTejaG** [comment]
@jesus-seijas-sp I would like to work on this. I'd also like to recommend doing it by using async/await with a promise being returned from inside the train method. If it's fine with that, I can start working on it immediately. 😄

**Comment by vvscode** [comment]
@IamRaviTejaG ooops. Sorry ((

**Comment by jesus-seijas-sp** [comment]
@IamRaviTejaG I will open another one because the example nlu-benchmark has the same problem, is doing the train() sync so the result is not the expected.

**Comment by jesus-seijas-sp** [comment]
Solved with https://github.com/axa-group/nlp.js/pull/78
Thank you @vvscode
