### ISSUE TITLE
Welcome message in Webchat 

### ISSUE THREAD

**Issue by nidhi-tib** [axa-group/nlp.js#781]
Hi, I am using node-nlp and it solves most of the purposes for me. However, I am stuck at this simple requirement where I need to show welcome message for the minimizable webchat example given. 
How can i do that ? the directline.say function needs activity which i am not sure how to get instance of. Also need to understand event that will help me identify that directline has started.

**Comment by jesus-seijas-sp** [comment]
Hello,
You'll need to get the directline plugin from your container, and add the **onCreateConversation** event.
It will receive the connector (the directline object again) and the conversation created in database(or memory), that contains the unique **conversationId** for this conversation. 
With this **conversationId** you can create a basic activity, and use it for sending a message to the conversation.

```javascript
  const directline = container.get('directline');
  directline.onCreateConversation = (connector, conversation) => {
    const activity = {
      conversation: {
        id: conversation.conversationId
      }
    }
    connector.say(activity, 'Hello!');
  }
```javascript

**Comment by nidhi-tib** [comment]
Thanks !!

**Comment by nidhi-tib** [comment]
my final index.js for reference ....

const { dockStart } = require('@nlpjs/basic');

(async () => {
  const dock = await dockStart();

  const directline = dock.get('directline');
  directline.onCreateConversation = (connector, conversation) => {
    const activity = {
      conversation: {
        id: conversation.conversationId
      }
    }
    connector.say(activity, <Welcome Message here>);
  }
})();

**Comment by ericzon** [comment]
As this topic has already been answered, I close it.
