### ISSUE TITLE
Can you pass variable to NLP?

### ISSUE THREAD

**Issue by MeetMartin** [axa-group/nlp.js#795]
Is it possible to pass a variable to NLP together with users utterance?

The idea is that frontend would be able to pass a variable with a request together with users utterance and the variable would then be used by the NLP in ops condition. Is that possible?

Also do opts condition allow only for simple equality or is it possible to use some basics javascript like myarray.includes(variable)?

Thank you for help

**Comment by jesus-seijas-sp** [comment]
Hello @MeetMartin, 

**nlp.process** accepts 4 parameters: locale, utterance, context and settings.

Supose that you have this intent:
```
intent test
  utterances
  - this is a test
  answers
  - You provided {{ id }} and {{ name }}
```
You can call it only with a sentence:
```javascript
nlp.process('this is a test');
// answer: You provided {{ id }} and {{ name }}
```

You can call it only with a locale and a sentence:
```javascript
nlp.process('en', 'this is a test');
// answer: You provided {{ id }} and {{ name }}
```
You can call it only with a locale, sentence and context:
```javascript
nlp.process('en', 'this is a test', { id: 7, name: 'John' });
// answer: You provided 7 and John
```
You can call it only with a sentence and context:
```javascript
nlp.process(undefined, 'this is a test', { id: 7, name: 'John' });
// answer: You provided 7 and John
```
You can call it only with a sentence and context but the sentence in the first position:
```javascript
nlp.process('this is a test', undefined, { id: 7, name: 'John' });
// answer: You provided 7 and John
```

**Comment by ericzon** [comment]
I think this topic has been answered, otherwise, reopen it.
