### ISSUE TITLE
NO GUI

### ISSUE THREAD

**Issue by jaksatomovic** [axa-group/nlp.js#800]
Is it possible to get a sentence from the mic and then extract intent from it only so I can invoke on intent custom func?

**Comment by jesus-seijas-sp** [comment]
Well, it's possible, but NLP.js is not in charge of hearing the mic neither doing the Speech to Text, it works only since you have the text sentence.

**Comment by ericzon** [comment]
I think this topic has been answered, otherwise, reopen it.
