### ISSUE TITLE
Optional less accurate entities extracted

### ISSUE THREAD

**Issue by mvillaizan** [axa-group/nlp.js#827]
Is there an option to get in the entity extraction payload a list of entities without removing less accurate results that overlap with other entities?

For example:

Adding an entity with a RegEx rule that is broad (in this case any text):

`ner.addRegexRule('en', 'free_input', new RegExp('(.+)\w+', 'gmi'));`

And then adding an entity with a set of values:

`ner.addRuleOptionTexts('en', 'state_name', 'CA', ['California', 'CA']);`

Extracting entities after those rules are added using an input that is missing a character (using distance to extract):

`
let input = 'Californi';
ner.process(input);
`

That would return only the RegEx entity extracted but not the text rule entity because the accuracy is less than 1 compared to the RegEx rule, is that correct?. Is there a way to have both entities return? This is using a threshold of `0.4`, the RegEx rule returns 1 accuracy and the Option Rule returns 0.9 (when the RegEx rule is removed we can see the option rule returned).

**Comment by mvillaizan** [comment]
The `runDiscard` function in the `reduce-edges.js` module seems to be doing this, is there a problem running `runDiscard` optionally?

**Comment by jesus-seijas-sp** [comment]
Well... there is not a problem about doint it optionally (default true) but based on a configuration parameter. 
The problem right now is about time... for me is impossible right now to dedicate time :( 
But I will be happy of code reviewing any PR.

**Comment by mvillaizan** [comment]
Thank you, will look into a PR.
