### ISSUE TITLE
different bot running different corpora

### ISSUE THREAD

**Issue by KongHongYi** [axa-group/nlp.js#844]
is it possible different bot running different corpora

{
  "pathPlugins": "./plugins",
  "pathPipeline": "./pipelines.md",
  "childs": {
    "bot1": {
      "settings": {
        "api-server": { "port": 3000, "serveBot": true },
      "nlp": {
        "corpora": [
          "./corpus.json"
        ]}
      },
      "use": ["ExpressApiServer", "DirectlineConnector"]
    },
    "bot2": {
      "settings": {
        "api-server": { "port": 3001, "serveBot": true },
        "nlp": {
          "corpora": [
            "./shop.json"
          ]}
      },
      "use": ["ExpressApiServer", "DirectlineConnector"]
    }
  },
  "use": ["Basic", "LangEn"]
}

like bot1 running corpus.json, but bot 2 running shop.json

**Comment by jesus-seijas-sp** [comment]
Take a look here: https://github.com/axa-group/nlp.js/issues/780

**Comment by KongHongYi** [comment]
https://github.com/axa-group/nlp.js/issues/780#issuecomment-754660273

in this part, the result i have is 
![result](https://user-images.githubusercontent.com/48196986/107354556-43204c80-6b09-11eb-8699-c8d8c02e19ee.PNG)

is 'undefined'
is it because i missing some part and causing the error?

**Comment by jesus-seijas-sp** [comment]
Well, those undefined are the console.log of the NER thresholds. Perhaps your config is different than the one in the example. 
I copy/pasted the example as is, tested, and the thresholds are shown in console.

**Comment by KongHongYi** [comment]
https://github.com/jesus-seijas-sp/nlpjs-examples/blob/master/01.quickstart/11.differentports/conf.json

I am using this conf.json. anything i need to add into this conf.json?

**Comment by jesus-seijas-sp** [comment]
You're focusing too much in those undefined. What those shows is the configuration of the threshold of the NER. If you don't configure a threshold, then the threshold is undefined, but this will be considered a 0.8 by default internally. 
You're using a conf.json that is not setting the threshold, but to be honest I don't even know if you're doing NER or doing only NLU.
Things you can do to don't see those undefined:
- Remove the console.log that shows them
- Set a threshold for your NER
