### ISSUE TITLE
conf.json file wildcards

### ISSUE THREAD

**Issue by marcpascualsanchez** [axa-group/nlp.js#846]
I am trying to import multiple dialogs and corpus dynamically.
Let's say I have a directory `./dialogs` with lots of dialogs and other directory `./corpus` also full of corpus files. I want to load all files from those directories in the `conf.json` file.
Is there any wildcard to achieve this easily? The `conf.json` could be like this:
```
{
    "settings": {
        "nlp": {
            "corpora": [
                "./corpus/*.json"
            ]
        },
        "bot": {
            "scripts": [
                "./dialogs/*.dlg"
            ]
        }
    },
    "use": [
        "Basic",
        "LangEn",
        "Bot"
    ]
}

```

**Comment by ericzon** [comment]
Hello @marcpascualsanchez to do this dynamically I suggest you to generate this json inside a .js file and pass it to dockStart

**Comment by marcpascualsanchez** [comment]
Yes, that was what I ended up doing, I just wondered if that was an option. I assume it is not. Thanks!
