### ISSUE TITLE
Number entity is not responding in NER

### ISSUE THREAD

**Issue by veeru76** [axa-group/nlp.js#853]
**Describe the bug**
A non-text  number is given for recognition and result appeared is empty. 

**To Reproduce**
1.  const response = await manager.process("en", " 259");
  console.log(JSON.stringify(response, null, 2));

{
  "locale": "en",
  "utterance": " 259",
  "languageGuessed": false,
  "localeIso2": "en",
  "language": "English",
  "nluAnswer": {
    "classifications": [
      {
        "intent": "None",
        "score": 1
      },
"intent": "None",
  "score": 1,
  "sourceEntities": [],
  "entities": [],
  "answers": [],
  "actions": [],
  "sentiment": {
    "score": 0,
    "numWords": 1,
    "numHits": 0,
    "average": 0,
    "type": "senticon",
    "locale": "en",
    "vote": "neutral"
  }

**Expected behavior**
number entity should be recognised

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10, 64 bit
 -chrome
 - node-nlp": "^4.17.2",

**Additional context**

**Comment by jesus-seijas-sp** [comment]
I'm testing it and seems to be working:
https://runkit.com/jesus-seijas-sp/602b76acaf5b0d001a392c4a
![image](https://user-images.githubusercontent.com/15154218/108032504-e229d480-7032-11eb-9588-e06d42689266.png)

**Comment by veeru76** [comment]
thank you, But I'm using duckling.the result is not changed

**Comment by veeru76** [comment]
thank you, But I'm using duckling.the result is not changed

**Comment by jesus-seijas-sp** [comment]
Tested with my duckling server, it works perfectly.
Are you sure that you're defining at least one intent with an entity in your corpus, or that you are setting forceNER to true so the NER is forced even if you don't have entities in your corpus?

```javascript
const { NlpManager } = require('node-nlp');

(async () => {
  const manager = new NlpManager({ languages: ['en'], forceNER: true, ducklingUrl: 'http://localhost:8000' });
  const response = await manager.process('en', '259');
  console.log(response);
})();
```

Response:

```
{
  locale: 'en',
  utterance: '259',
  settings: undefined,
  languageGuessed: false,
  localeIso2: 'en',
  language: 'English',
  nluAnswer: {
    classifications: [ [Object] ],
    entities: undefined,
    explanation: undefined
  },
  classifications: [ { intent: 'None', score: 1 } ],
  intent: 'None',
  score: 1,
  optionalUtterance: '%number%',
  sourceEntities: [
    {
      start: 0,
      end: 2,
      resolution: [Object],
      text: '259',
      typeName: 'number'
    }
  ],
  entities: [
    {
      start: 0,
      end: 2,
      len: 3,
      accuracy: 0.95,
      sourceText: '259',
      utteranceText: '259',
      entity: 'number',
      resolution: [Object]
    }
  ],
  answers: [],
  answer: undefined,
  actions: [],
  sentiment: {
    score: 0,
    numWords: 1,
    numHits: 0,
    average: 0,
    type: 'senticon',
    locale: 'en',
    vote: 'neutral'
  }
}
```

**Comment by veeru76** [comment]
Yes,I'm setting ForceNER to be true

**Comment by jesus-seijas-sp** [comment]
I revised my code:

```javascript
const { NlpManager } = require('node-nlp');

(async () => {
  const manager = new NlpManager({ languages: ['en'], forceNER: true,  ner: { ducklingUrl: 'http://localhost:8000/parse' }});
  const response = await manager.process('en', '259');
  console.log(response);
})();
```
This is working.
If the URL is not correct, then the exception is shown in console:

![image](https://user-images.githubusercontent.com/15154218/108061191-3dba8900-7058-11eb-91ae-dc32aff11bd0.png)

Otherwise, I suggest you to debug with breakpoint in node_modules/@nlpjs/builtin-duckling at the first line of run funcion, and see what is happening.

**Comment by veeru76** [comment]
sure,thank you
