### ISSUE TITLE
¿How to use addNamedEntityText on version 4?

### ISSUE THREAD

**Issue by medisoft** [axa-group/nlp.js#854]
Hi! I'm willing to use named entities to get information about the user, with slots. The documentation I found is for v3, and I'm asking if the v4 has something that is compatible.

Because the documentation for v4 is not very complete, and could't find any examples on how to implement asking for information to the user.

I tried to create a slot, with the intend and entity and multilanguage questions, but was not able to get the data from the user.

Thanks

**Comment by sandro-pasquali** [comment]
I too would be thankful for a v4 version of the examples on this page: https://github.com/axa-group/nlp.js/blob/master/docs/v3/slot-filling.md

The above is v3, which is linked from the TOC[slot filling] entry in readme.

Fantastic lib!

**Comment by ericzon** [comment]
Hello, take a look this test as example: https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/packages/node-nlp/test/nlp/nlp-manager.test.js
it's using node-nlp package, that tries to keeps compatibility with v3 style.
Anyway, I suggest to take a different approach to get something like slot filling, check [v4 bot orchestration topic](https://github.com/axa-group/nlp.js/issues/715)

**Comment by ericzon** [comment]
Topic closed due to inactivity.
