### ISSUE TITLE
Open Questions in NLP.JS

### ISSUE THREAD

**Issue by ignStonechat** [axa-group/nlp.js#861]
# Is it possible to do open questions in NLP.JS and how
So, basically before you guys say it, I've searched around on here but haven't found GOOD answer to my question.
Is it possible to make open questions in nlp.js and if so HOW!
I found a package called "@nlpjs/open-question" but no docs, no nothing.

**Comment by ignStonechat** [comment]
so basically I got no response in abt 24hrs. so I decided to make history system with cleanup algorithm I made few months ago. it works fine and goes O K and is similar to having common sense.

**Comment by jesus-seijas-sp** [comment]
Well, you have an example here: https://github.com/axa-group/nlp.js/tree/master/examples/81-bert-qna
Basically it creates a server in python, with a deep-pavlov (also BERT tokenizer).
The part of python that points to deep-pavlov can be replaced with BERT with the model you choose.

You'll find this in the config.json, pay attention to "open-question" part of the config. There are two contexts, it creates a bot that you can access at http://localhost:3000 and make questions about the context, at this article at section 3 you have a gif showing this: https://medium.com/just-tech-it-now/getting-started-with-nlp-js-68706c663d49
```
{
  "pathPlugins": "./plugins",
  "pathPipeline": "./pipelines.md",
  "settings": {
    "nlp": {
      "languages": ["en", "es"]
    },
    "open-question": {
      "url": "http://localhost:8000/qna",
      "context-en": "The first book title is the philosopher stone. The second book title is the chamber of secrets. The third book is the prisioner of Azkaban",
      "context-es": "El título del primer libro es la piedra filosofal. El título del segundo libro es la cámara de los secretos. El tercer libro es el prisionero de Azkaban"

    },
    "api-server": { "port": 3000, "serveBot": true }
  },
  "use": [
    { "className": "logger", "path": "../../packages/logger/src" },
    { "className": "Nlp", "path": "../../packages/nlp/src" },
    { "className": "LangEn", "path": "../../packages/lang-en/src" },
    { "className": "ExpressApiServer", "path": "../../packages/express-api-server/src" },
    { "className": "DirectlineConnector", "path": "../../packages/directline-connector/src" },
    { "className": "BertOpenQuestion", "path": "../../packages/bert-open-question/src" }
  ]
}
```

**Comment by ignStonechat** [comment]
Oh! Thank you so much!! really helpful this is officially closed!
