### ISSUE TITLE
Fail over to Spanish?

### ISSUE THREAD

**Issue by j2l** [axa-group/nlp.js#91]
**Describe the bug**
When guessing very short utterance, classification is correct but language is guessed as Spanish, hence not throwing english reply.

**To Reproduce**
NLP:
![image](https://user-images.githubusercontent.com/65325/46919332-5a54db00-cfde-11e8-85e1-7287652604b2.png)

NLG:
![image](https://user-images.githubusercontent.com/65325/46919340-6e004180-cfde-11e8-8095-e35719647223.png)

User: `dfgdfg@fgdd.gg`
AxaBot: 
`Sorry, I don't understand, {"locale":"es","localeIso2":"es","language":"Spanish","utterance":"dfgdfg@fgdd.gg","classification":[{"label":"email2","value":0.9819053927264487},{"label":"email","value":0.6188665942300879},{"label":"realname","value":0.12743325382186388},{"label":"whois","value":0.08484683107101253},{"label":"whereis","value":0.08484683107101253},{"label":"hashtag","value":0.029910769295364337}],"intent":"email2","domain":"default","score":0.9819053927264487,"entities":[{"start":0,"end":14,"accuracy":1,"sourceText":"dfgdfg@fgdd.gg","utteranceText":"dfgdfg@fgdd.gg","entity":"mail"}],"sentiment":{"score":0,"comparative":0,"vote":"neutral","numWords":3,"numHits":0,"type":"senticon","language":"es"}}.`

**Expected behavior**
Default to any chosen language, or best, be able to force language for this input (once we guessed preferred language using prior talks guesses and wrote to user's settings).

**Comment by j2l** [comment]
Great, we have options.

> pass the language to the NlpManager.process

how would you do that for only one process?

BTW, I had this behavior only with `en` language set in NLP sheet, no `es` for %mail% in this case.
Does builtin email recognition has a default language?

**Comment by jesus-seijas-sp** [comment]
This is a piece of code from the process:

```
/**
   * Process an utterance for full classify and analyze. If the locale is
   * not provided, then it will be guessed.
   * Classify the utterance and extract entities from it, returning an
   * object with all the information available.
   * Also calculates the sentiment of the utterance, if possible.
   * @param {String} srcLocale Language locale of the utterance.
   * @param {String} srcUtterance Text of the utterance.
   * @param {Promise.Object} Promise srcContext Context for finding answers.
   */
  async process(srcLocale, srcUtterance, srcContext) {
    let utterance = srcUtterance;
    let locale = srcLocale;
    let languageGuessed = false;
    if (!utterance) {
      utterance = locale;
      locale = this.guessLanguage(utterance);
      languageGuessed = true;
    }
```

So you can call process passing the locale as first parameter so the language will not be guessed: ```manager.process('en', 'your utterance', context)```. If you don't provide the language then is guessed, but is guessed before procesing the intents or the entities.

**Comment by j2l** [comment]
👍 Perfect!

And does builtin email recognition has a default language? Because I didn't have `es` in my case.

**Comment by jesus-seijas-sp** [comment]
Well, 'es' is not hardcoded anywhere... The only place is in the tests, and in the excel at the first page. Can you provide an example of code? 
The language at the builtins is very important because it also understand currencies, or numbers or ordinals text written... you can check it by passing "My number is one hundred and twenty two". It works also in spanish, portuguese, chinese, japanese...

**Comment by j2l** [comment]
Ok, so it did a random guess. 
I didn't try with another email address, I may get another language.
Actually, I'm only testing with the XLS you provide, just added the content seen in the screenshots to do tests.
Never mind it was a side effect of a singleton case about a non-language input.
Fixed for me!

Thanks again for the quickness in replying. It really helps stay motivated.
