### ISSUE TITLE
Train nlp with text extracted from messages

### ISSUE THREAD

**Issue by realrecordzLab** [axa-group/nlp.js#931]
Is possible to train the nlp and console connector with the text extracted from some messages? 
I'm working on a chatbot that will need to learn from messages sent from facebook or instagram DM and give to the user a reply, I've seen the documentations about QnA but in my case I don't have a series of questions because I'm not able to predict what the user will ask.

**Comment by ericzon** [comment]
If you don't have defined in advance which are the topics that will be covered by the chatbot, it will be complex to do it in an automated way, I mean, you can do it, but this can require a kind of validation to try to avoid users pollute your corpus with wrong data. From the user inputs, how will you identify what is useful?
Of course, you can store the user inputs and retrain the model once you had enough new data, but is needed more than this to get a successful bot.

**Comment by ericzon** [comment]
Closed due to inactivity

**Comment by realrecordzLab** [comment]
@ericzon I have a telegram bot script mande with node-telegram-bot-api and I want to extract from user input messages to create a natural conversation experience, I'm planning to drive the conversation from the welcome message, then give two replies to the user that than will start to train the nlp script.

example
```js
#!/usr/bin/env node

const TelegramBot = require('node-telegram-bot-api');
const process = require('process');
const axios = require('axios').default;

// replace the value below with the Telegram token you receive from @BotFather
const token = process.env.TELEGRAM_BOT_TOKEN || '5252802474:A';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});

let suggestedCams = [];

// Matches "/echo [whatever]"
bot.onText(/\/echo(.+)/, async (msg, match) => {
  // 'msg' is the received Message from Telegram
  // 'match' is the result of executing the regexp above on the text content
  // of the message
  console.log(msg);

  const chatId = msg.chat.id;
  //const gender = match[1]; // the captured "whatever"
  const init = match[1];
  console.log(init);
});

// Listen for any kind of message. There are different kinds of
// messages.
let currentUser = ''; 

bot.on('message', (msg) => {

  const chatId = msg.chat.id;
  currentUser = msg.from.first_name;
  console.log(msg);
  const welcomeMessage = `${currentUser} I'm listeniing to you. please explain me better how I can help you. You need to just talk?.`;
  // send a message to the chat acknowledging receipt of their message
 // from here I want to implement nlp to train with text input like an initial QnA
  bot.sendMessage(chatId, welcomeMessage);
});

```
