### ISSUE TITLE
Migrate codebase to Typescript

### ISSUE THREAD

**Issue by vvscode** [axa-group/nlp.js#94]
What about migrating codebase to TS?  Not the whole codebase in one time, but at least add support for tsc  to make at possible add types further.

**Comment by shadow1349** [comment]
I really like this library, but it's a pain to use in TypeScript. @jesus-seijas-sp you guys wouldn't have to rewrite the whole thing you guys could publish a library in the DefinitelyTyped repo so you could have an @types/nlp.js package. It would be minimal effort.

**Comment by miloshavlicek** [comment]
@jesus-seijas-sp Is there any plan to support Typescript types? E.g. by creating DefinitelyTyped repo @types/node-nlp?

**Comment by luddilo** [comment]
+1, this would be very useful

**Comment by msolefonte** [comment]
Push for the @types/node-nlp repository. It would be a really good addition.
