### ISSUE TITLE
Just a little description problem

### ISSUE THREAD

**Issue by fabiooshiro** [axa-group/nlp.js#951]
test('It should return **true** if at least one item in array exists in dictionary', () => {

https://github.com/axa-group/nlp.js/blob/167bd285463ca3a21b549c0961a4d87b72ac8a8c/packages/nlu/test/nlu.test.js#L267

**frist**

https://github.com/axa-group/nlp.js/blob/167bd285463ca3a21b549c0961a4d87b72ac8a8c/packages/nlu/test/nlu-manager.test.js#L416

**Comment by ericzon** [comment]
Thanks for reporting, it was put on purpose to stimulate Hacktoberfest, just joking :) 
Fixed! https://github.com/axa-group/nlp.js/commit/b6bfe873c1564dab4af0f85938de551b514d74f6
