### ISSUE TITLE
Nlp Manager : is not a function

### ISSUE THREAD

**Issue by saptisunil** [axa-group/nlp.js#959]
I am not able to use NlpManager as it shows NlpManager is not a function. How can we solve this? Also i would like to know how Nlp learns from user interactions?

**Comment by ericzon** [comment]
hello @saptisunil, nlp manager is from a previous version v3 although if you prefer keep using nlpManager, a package [@nlp.js/node-nlp](https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/packages/node-nlp/src/nlp/index.js) was created to keep some compatibility with older versions. Please, take a look at the examples ([90-benchmark](https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/examples/90-benchmark/index.js), [node-nlp tests](https://github.com/axa-group/nlp.js/blob/5a0dfc580410c15d355851a8f852e81a70cff1f4/packages/node-nlp/test/nlp/nlp-manager.test.js)).

I put this as a sample:
```
const { NlpManager } = require('node-nlp');

const corpus = require('./corpus-en.json');

(async () => {
  const nlp = new NlpManager();
  nlp.addCorpus(corpus);
  await nlp.train();
  const actual = await nlp.process('who are you?');
  console.log('response', actual);
})();
```


To learn from interactions, you'll need to monitor user inputs and which scores they got from NLP processing.
If you want to track full conversation, you can do this checking at the activities stored per conversation.
Dialog flows (not available in v3) can be tracked in different ways but the easiest one is checking the context collection. 


I hope it helps

**Comment by saptisunil** [comment]
@ericzon Thank you for replying me. I would like to know from where do i get to see the context collection.

**Comment by saptisunil** [comment]
@ericzon Hello, Still after using from node-nlp i am able to get the error NlpManager is not a constructor. How can i solve this?
![image](https://user-images.githubusercontent.com/69889574/127604818-e1fad9d9-ea82-4da3-9ae4-51e843a12e90.png)

**Comment by ericzon** [comment]
I've just tried a code like I shared before on node.js v14.15.5 and I don't experience any issue.

![image](https://user-images.githubusercontent.com/1809508/128782976-9bbf8a00-6081-4db2-ad51-d5799636bc98.png)

Did you have any problem with the code I provided + a valid corpus?
Please, take a look to this https://github.com/axa-group/nlp.js/issues/795 about using the context.

**Comment by ericzon** [comment]
Closing due inactivity & this topic is already answered

**Comment by iamjohnsimeon** [comment]
I have a similar [issue](https://github.com/axa-group/nlp.js/issues/1251). 
Perhaps some clarity to the documentation. 
I'm getting `manager.registerActionFunction is not a function`.
I noticed you mentioned "nlp manager is from a previous version v3" what is the package to be used in version v4?

**Comment by Apollon77** [comment]
The current Git version is not yet released and should be released soon ... after that it should solve
