### ISSUE TITLE
Create a type of entity

### ISSUE THREAD

**Issue by TahianaRakotolobo** [axa-group/nlp.js#972]
Hi. Is it possible to create a new type of entity? If it is, then could you tell me how to do that? Thank you.

**Comment by ericzon** [comment]
Please @TahianaRakotolobo  take a look into [ner examples](https://github.com/axa-group/nlp.js/tree/master/examples/14-ner-corpus)

**Comment by ericzon** [comment]
I close this as this question is already answered
